### ISSUE TITLE
Easiest way to install?

### ISSUE THREAD

**Issue by TogarUshindi** [DadSchoorse/vkBasalt#101]
Back during version 0.3.0 I discovered vkBasalt through Chris Titus Tech and mimicked his [demonstration](https://www.youtube.com/watch?v=6p1SNBy4P74) for installing. Was very easy. `make install`. Unfortunately, now it looks like we need a new dependency called [glslang](https://github.com/KhronosGroup/glslang)? I visited that repository and it appears it requires even more dependencies. They seem more geared toward developers than end-users. Nonetheless I downloaded the binary, and now I'm not sure what to do. I'm Ubuntu 20.04 LTS.

```
$ meson --buildtype=release --prefix=/usr builddir
The Meson build system
Version: 0.53.2
Source dir: /home/user/apps/PoE-stuff/vkBasalt
Build dir: /home/user/apps/PoE-stuff/vkBasalt/builddir
Build type: native build
Project name: vkBasalt
Project version: undefined
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
C++ compiler for the host machine: c++ (gcc 9.3.0 "c++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program glslangValidator found: NO

src/shader/meson.build:17:0: ERROR: Program(s) ['glslangValidator'] not found or not executable

A full log can be found at /home/user/apps/PoE-stuff/vkBasalt/builddir/meson-logs/meson-log.txt
```

**Comment by Waddlen** [comment]
It looks like [Ubuntu packages it](https://packages.ubuntu.com/search?keywords=glslang-dev), can't you just `sudo apt install glslang-dev`?

**Comment by TogarUshindi** [comment]
Ah, thank you!

Okay, so I just installed that, and same error is coming up:

```
Program glslangValidator found: NO

src/shader/meson.build:17:0: ERROR: Program(s) ['glslangValidator'] not found or not executable
```

**Comment by stephanlachnit** [comment]
> It looks like [Ubuntu packages it](https://packages.ubuntu.com/search?keywords=glslang-dev), can't you just `sudo apt install glslang-dev`?

Wrong package, see [here](https://packages.debian.org/search?searchon=contents&keywords=glslangValidator&mode=path&suite=unstable&arch=any). @TogarUshindi you need `sudo apt install glslang-tools`.
