### ISSUE TITLE
Error: Program glslangValidator found: NO

### ISSUE THREAD

**Issue by CHJ85** [DadSchoorse/vkBasalt#110]
Hi there. While executing the installation command, it tells me "Program glslangValidator found: NO".
What is this about?
And you also said in the instruction not to use --prefix=/usr, but in the command below you included it in there.
A bit confused as to what I should do here.
How much extra work would it be for you to add vkBasalt to the Ubuntu repo? Because this compiling stuff is a bit too overwhelming and scary.

**Comment by mrpotatofactory** [comment]
Try this:

```
mkdir temp
cd temp

wget https://github.com/KhronosGroup/glslang/releases/download/master-tot/glslang-master-linux-Release.zip
unzip glslang-master-linux-Release.zip

mv bin/* /usr/local/bin/
mv lib/* /usr/local/lib/
mv include/* /usr/local/include/

cd ..
rm temp -rfv
```

**Comment by CHJ85** [comment]
@mrpotatofactory Yes, that worked.
Thank you so much! 😀
