### ISSUE TITLE
Cannot compile!

### ISSUE THREAD

**Issue by Ohio2** [DadSchoorse/vkBasalt#113]
Directory already configured.

Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
If ninja fails, run "ninja reconfigure" or "meson --reconfigure"
to force Meson to regenerate.

If build failures persist, run "meson setup --wipe" to rebuild from scratch
using the same options as passed when configuring the build.
To change option values, run "meson configure" instead.
ninja: Entering directory `builddir'
[1/33] Compiling C++ object 'src/reshade/483b4fb@@reshade@sta/effect_preprocessor.cpp.o'.
FAILED: src/reshade/483b4fb@@reshade@sta/effect_preprocessor.cpp.o 
c++ -Isrc/reshade/483b4fb@@reshade@sta -Isrc/reshade -I../src/reshade -I.././include -I.././include/spirv -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++2a -O3 -fPIC  -MD -MQ 'src/reshade/483b4fb@@reshade@sta/effect_preprocessor.cpp.o' -MF 'src/reshade/483b4fb@@reshade@sta/effect_preprocessor.cpp.o.d' -o 'src/reshade/483b4fb@@reshade@sta/effect_preprocessor.cpp.o' -c ../src/reshade/effect_preprocessor.cpp
../src/reshade/effect_preprocessor.cpp: In member function ‘void reshadefx::preprocessor::parse_include()’:
../src/reshade/effect_preprocessor.cpp:659:11: error: ‘find_if’ is not a member of ‘std’
  if (std::find_if(_input_stack.begin(), _input_stack.end(),
           ^~~~~~~
../src/reshade/effect_preprocessor.cpp:659:11: note: suggested alternative: ‘find’
  if (std::find_if(_input_stack.begin(), _input_stack.end(),
           ^~~~~~~
           find
../src/reshade/effect_preprocessor.cpp: In member function ‘void reshadefx::preprocessor::create_macro_replacement_list(reshadefx::preprocessor::macro&)’:
../src/reshade/effect_preprocessor.cpp:1193:105: error: no matching function for call to ‘find(std::vector<std::__cxx11::basic_string<char> >::iterator, std::vector<std::__cxx11::basic_string<char> >::iterator, std::__cxx11::string&)’
     const auto it = std::find(macro.parameters.begin(), macro.parameters.end(), _token.literal_as_string);
                                                                                                         ^
In file included from /usr/include/c++/8/bits/locale_facets.h:48,
                 from /usr/include/c++/8/locale:40,
                 from /usr/include/c++/8/bits/fs_path.h:38,
                 from /usr/include/c++/8/filesystem:37,
                 from ../src/reshade/effect_preprocessor.hpp:10,
                 from ../src/reshade/effect_preprocessor.cpp:7:
/usr/include/c++/8/bits/streambuf_iterator.h:368:5: note: candidate: ‘template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)’
     find(istreambuf_iterator<_CharT> __first,
     ^~~~
/usr/include/c++/8/bits/streambuf_iterator.h:368:5: note:   template argument deduction/substitution failed:
../src/reshade/effect_preprocessor.cpp:1193:105: note:   ‘__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >’ is not derived from ‘std::istreambuf_iterator<_CharT>’
     const auto it = std::find(macro.parameters.begin(), macro.parameters.end(), _token.literal_as_string);
                                                                                                         ^
../src/reshade/effect_preprocessor.cpp:1212:108: error: no matching function for call to ‘find(std::vector<std::__cxx11::basic_string<char> >::iterator, std::vector<std::__cxx11::basic_string<char> >::iterator, std::__cxx11::string&)’
    if (const auto it = std::find(macro.parameters.begin(), macro.parameters.end(), _token.literal_as_string);
                                                                                                            ^
In file included from /usr/include/c++/8/bits/locale_facets.h:48,
                 from /usr/include/c++/8/locale:40,
                 from /usr/include/c++/8/bits/fs_path.h:38,
                 from /usr/include/c++/8/filesystem:37,
                 from ../src/reshade/effect_preprocessor.hpp:10,
                 from ../src/reshade/effect_preprocessor.cpp:7:
/usr/include/c++/8/bits/streambuf_iterator.h:368:5: note: candidate: ‘template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)’
     find(istreambuf_iterator<_CharT> __first,
     ^~~~
/usr/include/c++/8/bits/streambuf_iterator.h:368:5: note:   template argument deduction/substitution failed:
../src/reshade/effect_preprocessor.cpp:1212:108: note:   ‘__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >’ is not derived from ‘std::istreambuf_iterator<_CharT>’
    if (const auto it = std::find(macro.parameters.begin(), macro.parameters.end(), _token.literal_as_string);
                                                                                                            ^
[6/33] Compiling C++ object 'src/25a6634@@vkbasalt@sha/effect_fxaa.cpp.o'.
ninja: build stopped: subcommand failed.

**Comment by DadSchoorse** [comment]
Looks like you are using gcc8, but vkBasalt requires gcc9+.

**Comment by Ohio2** [comment]
Okay, that's fine i guess, thanks!
