### ISSUE TITLE
Doesn't work on Steam

### ISSUE THREAD

**Issue by guglovich** [DadSchoorse/vkBasalt#116]
Stopped working on Steam, I don't know after what update the problem appeared. Works through Wine as before.

**Comment by DadSchoorse** [comment]
I'm pretty sure it only doesn't work with Proton 5.13.

> - System-wide Vulkan layers like MangoHUD or vkBasalt don't work

https://github.com/ValveSoftware/Proton/issues/4289
Maybe try Proton 5.0 to confirm that there's no other issue.

**Comment by guglovich** [comment]
With 5.0.9 it works, yes. Got it.

**Comment by guglovich** [comment]
Will the work be implemented for version 4.11-13?
