### ISSUE TITLE
World of Warcraft Shadowlands and Classic crashes to Desktop

### ISSUE THREAD

**Issue by lavadrop** [DadSchoorse/vkBasalt#117]
Just that. Battle.net Launcher loads it's login window, then the launcher crashes instantly, won't even load the actual wow executable. Using Wine-Staging 5.19 via PlayOnLinux precompiled binary with vkd3d. Also crashes WoW Classic using the Lutris-bundled Wine 5.7.6 running DXVK.

I'm attaching the lutris crash log.
[lutris vkbasalt crash.txt](https://github.com/DadSchoorse/vkBasalt/files/5425331/lutris.vkbasalt.crash.txt)

**Comment by DadSchoorse** [comment]
> `vkBasalt info:  effects = :cas`

There's your issue, only use `:` to separate effects, not at the end or start of the list.

**Comment by lavadrop** [comment]
Thanks, however I'm using GOverlay, I never tweaked it manually. I'll take a look at their issues in their repo.
