### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by stephanlachnit** [DadSchoorse/vkBasalt#120]
@DadSchoorse can you tag a new release? I want to present vkBasalt at the MiniDebConf (topic is gaming), and it would be cool to have a package by then.

**Comment by DadSchoorse** [comment]
Done.

**Comment by stephanlachnit** [comment]
Thanks :+1:

**Comment by stephanlachnit** [comment]
Good news, vkBasalt got accepted into Debian: https://tracker.debian.org/pkg/vkbasalt

Once the binary builds are up I will open a PR to add install instructions (since it won't be included in a release until Debian 11 / Ubuntu 21.04, which both will release in about half a year, but you can still download the .deb manually).
