### ISSUE TITLE
Vulkan headers

### ISSUE THREAD

**Issue by stephanlachnit** [DadSchoorse/vkBasalt#121]
Quick question - why do you need to ship all the Vulkan headers? They should be available on most distros.

If you need really recent headers you could do it simply with the Meson Wrap like [here](https://github.com/flightlessmango/MangoHud/pull/196) (it super easy to update the Wrap in case 1.2.142 isn't recent enough).

**Comment by DadSchoorse** [comment]
I started shipping them because some distro's Vulkan headers were incompatible with their Vulkan Validation Layers headers.

**Comment by stephanlachnit** [comment]
Lol that sounds hilarious. Which distros?

**Comment by DadSchoorse** [comment]
I think that time it was Arch.

**Comment by stephanlachnit** [comment]
Back to the topic: I think I should be able to write up Wraps for both the headers and the validation layers, so they can be used optionally without cluttering the sources.

**Comment by stephanlachnit** [comment]
Alright, so the Vulkan-Headers 1.2.158 are now in Wrap DB (https://wrapdb.mesonbuild.com/vulkan-headers), and I opened a PR for Vulkan-ValidationLayers 1.2.158 (https://github.com/mesonbuild/vulkan-validationlayers/pull/1).

I will open a PR as soon as the ValidationsLayers are merged. We can then replace the headers with two small files (one for each repo), and users can optionally download and compile with the upstream sources instead of the system headers.

If I'm already cleaning up, can we get rid of the two SPIR-V headers as well? I can write a Wrap for it if there are problems with some distros.
