### ISSUE TITLE
Does not work in Lineage 2

### ISSUE THREAD

**Issue by guglovich** [DadSchoorse/vkBasalt#128]
Stopped working in Lineage 2, a month ago everything was fine.

**Comment by DadSchoorse** [comment]
1. Are you using Proton 5.13? The steam runtime breaks global vulkan layers. https://github.com/ValveSoftware/Proton/issues/4289
2. If you are using the aur do you also have lib32-vkBasalt installed? They have split the package in 64bit and 32bit.

**Comment by guglovich** [comment]
>     2\. If you are using the aur do you also have lib32-vkBasalt installed? They have split the package in 64bit and 32bit.

Thanks, I didn't know they split the packages. Everything works now.
