### ISSUE TITLE
fail to compile on Fedora 33

### ISSUE THREAD

**Issue by tuxtergames** [DadSchoorse/vkBasalt#130]
after trying to compiling a few times I have the same error here

[output.log](https://github.com/DadSchoorse/vkBasalt/files/5586308/output.log)

**Comment by tuxtergames** [comment]
> after trying to compiling a few times I have the same error here, I know abbout rpmfusion version, but I use this one.
> 
> [output.log](https://github.com/DadSchoorse/vkBasalt/files/5586308/output.log)

**Comment by DadSchoorse** [comment]
You need to install `spirv-headers` along with the other dependencies listed here: https://github.com/DadSchoorse/vkBasalt#dependencies

**Comment by tuxtergames** [comment]
> You need to install `spirv-headers` along with the other dependencies listed here: https://github.com/DadSchoorse/vkBasalt#dependencies

Tks, working here!
