### ISSUE TITLE
Hanging on Battle Net

### ISSUE THREAD

**Issue by guglovich** [DadSchoorse/vkBasalt#132]
Hanging in the launcher when vkBasalt is on. Tested on Wine-Staging and PortProton.

**Comment by DadSchoorse** [comment]
I need a log to look into it.

**Comment by guglovich** [comment]
[error.log.zip](https://github.com/DadSchoorse/vkBasalt/files/5625491/error.log.zip)

**Comment by guglovich** [comment]
Irrelevant for 2022. Works.
