### ISSUE TITLE
Glitches on image borders

### ISSUE THREAD

**Issue by pchome** [DadSchoorse/vkBasalt#136]
There are minor glitches on the image borders with some effects. Most visible for `fxaa`, hard to note but likely present for other builtin effects. Not present (or not visible) for Reshade effects, or visible if mixed with builtin `fxaa` effect.

See example (open in separate tab and check out image borders):
![](https://user-images.githubusercontent.com/10661854/103136950-5c8e4600-46cd-11eb-86c2-0bafdb0584fb.png)

Symptoms: when one side is darker and other is lighter then some light pixels from one side reflected on other's side border. And vice-versa. Looks like there is constant ~1px reflection of top-bottom and left-right pixels.

**Comment by DadSchoorse** [comment]
It's probably a sampler addressing issue, we shouldn't use `VK_SAMPLER_ADDRESS_MODE_REPEAT` here. I will take a look when I have access to my pc again.

**Comment by DadSchoorse** [comment]
Please retest with 77ec88d41773273bb7e67beece1e686cca4c5188.

**Comment by pchome** [comment]
Looks fixed.
