### ISSUE TITLE
Vkbasalt doesn't work

### ISSUE THREAD

**Issue by JulioSordi** [DadSchoorse/vkBasalt#140]
I'm in Manjaro KDE, i've installed vkbasalt from AUR and configured it with GOverlay, it seems that vkbasalt simply isn't working in any of my games regardless if i run through Steam or Lutris.

**Comment by DadSchoorse** [comment]
Please post the output of `VK_LOADER_DEBUG=all ENABLE_VKBASALT=1 vkcube`.

**Comment by JulioSordi** [comment]
> VK_LOADER_DEBUG=all ENABLE_VKBASALT=1 vkcube

ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 1011015 for game ID 33554432
>>> Adding process 1011017 for game ID 33554432
pid 1011484 != 1011010, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 1011488 for game ID 33554432
ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 1011490 for game ID 33554432
ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 1011491 for game ID 33554432
ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 1011492 for game ID 33554432
fsync: up and running.
>>> Adding process 1011493 for game ID 33554432
ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 1011496 for game ID 33554432
ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 1011498 for game ID 33554432
ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 1011501 for game ID 33554432
ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 1011509 for game ID 33554432
ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 1011515 for game ID 33554432
ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 1011528 for game ID 33554432
RecordSteamInterfaceCreation (PID 1011492): SteamUtils009 / Utils
[S_API FAIL] SteamAPI_Init() failed; no appID found.
Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

ERROR: ld.so: object '/home/julio/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 1011586 for game ID 33554432
Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Application Data\openvr\openvrpaths.vrpath
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Installing breakpad exception handler for appid(gameoverlayui)/version(20201220230711)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
[0110/171807.879863:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
[0110/171808.051698:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
pid 1011494 != 1011493, skipping destruction (fork without exec?)
Game removed: AppID 0 "Need for Speed Most Wanted", ProcID 1011586 
Uploaded AppInterfaceStats to Steam

**Comment by nariox** [comment]
You need to run `vkcube`, not on Steam. The problem on steam is that since proton 5.13, they are using a container to run the games, so any external library doesn't get loaded.

First try with vkcube, then try with Proton 5.10. If those work, then you can try to figure out how to get around the container.

**Comment by JulioSordi** [comment]
> You need to run `vkcube`, not on Steam. The problem on steam is that since proton 5.13, they are using a container to run the games, so any external library doesn't get loaded.
> 
> First try with vkcube, then try with Proton 5.10. If those work, then you can try to figure out how to get around the container.

Proton 5.10 fails to launch, i have tried many Proton and Proton GE versions, Mangohud doesn't work in any of them, only works with terminal commands such as glxgear and vkcube

**Comment by JulioSordi** [comment]
mangohud vkcube
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/julio/.config/MangoHud/vkcube.conf [ not found ]
parsing config: /home/julio/.config/MangoHud/MangoHud.conf [ ok ]
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
MANGOHUD: Failed to load NVML
MANGOHUD: XNVCtrl didn't find the correct display
MANGOHUD: Uploading is disabled (permit_upload = 0)
MANGOHUD: recreating font image

**Comment by nariox** [comment]
Do you have a NVIDIA card? Or intel?

Does Proton 5.10 work without vkbasalt? What about mangohud?

**Comment by JulioSordi** [comment]
> Do you have a NVIDIA card? Or intel?
> 
> Does Proton 5.10 work without vkbasalt? What about mangohud?

No it doesn't work without vkbasalt, mangohud doesn't work either, i have an Intel UHD 620

**Comment by koubel** [comment]
Hi,
for me vkBasalt stopped working as well for combo **Witcher3 + Steam + Proton 5.13-5** 
I have fixed the issue with copying the "`libvkbasalt.so`" file into Steam's Soldier lib dirs.

Just seek for a directory "`x86_64-linux-gnu`" in your steam apps directories and place the "libvkbasalt.so" file there.
For me it was:
...`steamapps/common/SteamLinuxRuntime_soldier/soldier_0.20210105.2/files/lib/x86_64-linux-gnu/libvkbasalt.so`
...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/steam-runtime-tools-0/libvkbasalt.so`
...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/libvkbasalt.so`

I am not using "`ENABLE_VKBASALT=1 %command%`" in Steam , instead I have directive "`export ENABLE_VKBASALT=1`" placed in the end of my `.profile` file.

My system is Kubuntu 20.10 , nVidia with nV drivers 460.32.03 , intel CPU

Hope this will help!

**Comment by JulioSordi** [comment]
> Hi,
> for me vkBasalt stopped working as well for combo **Witcher3 + Steam + Proton 5.13-5**
> I have fixed the issue with copying the "`libvkbasalt.so`" file into Steam's Soldier lib dirs.
> 
> Just seek for a directory "`x86_64-linux-gnu`" in your steam apps directories and place the "libvkbasalt.so" file there.
> For me it was:
> ...`steamapps/common/SteamLinuxRuntime_soldier/soldier_0.20210105.2/files/lib/x86_64-linux-gnu/libvkbasalt.so`
> ...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/steam-runtime-tools-0/libvkbasalt.so`
> ...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/libvkbasalt.so`
> 
> I am not using "`ENABLE_VKBASALT=1 %command%`" in Steam , instead I have directive "`export ENABLE_VKBASALT=1`" placed in the end of my `.profile` file.
> 
> My system is Kubuntu 20.10 , nVidia with nV drivers 460.32.03 , intel CPU
> 
> Hope this will help!

The file is already there in my case

**Comment by JulioSordi** [comment]
> Hi,
> for me vkBasalt stopped working as well for combo **Witcher3 + Steam + Proton 5.13-5**
> I have fixed the issue with copying the "`libvkbasalt.so`" file into Steam's Soldier lib dirs.
> 
> Just seek for a directory "`x86_64-linux-gnu`" in your steam apps directories and place the "libvkbasalt.so" file there.
> For me it was:
> ...`steamapps/common/SteamLinuxRuntime_soldier/soldier_0.20210105.2/files/lib/x86_64-linux-gnu/libvkbasalt.so`
> ...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/steam-runtime-tools-0/libvkbasalt.so`
> ...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/libvkbasalt.so`
> 
> I am not using "`ENABLE_VKBASALT=1 %command%`" in Steam , instead I have directive "`export ENABLE_VKBASALT=1`" placed in the end of my `.profile` file.
> 
> My system is Kubuntu 20.10 , nVidia with nV drivers 460.32.03 , intel CPU
> 
> Hope this will help!

Where is this lbvkbasalt.so located?

**Comment by koubel** [comment]
> > Hi,
> > for me vkBasalt stopped working as well for combo **Witcher3 + Steam + Proton 5.13-5**
> > I have fixed the issue with copying the "`libvkbasalt.so`" file into Steam's Soldier lib dirs.
> > Just seek for a directory "`x86_64-linux-gnu`" in your steam apps directories and place the "libvkbasalt.so" file there.
> > For me it was:
> > ...`steamapps/common/SteamLinuxRuntime_soldier/soldier_0.20210105.2/files/lib/x86_64-linux-gnu/libvkbasalt.so`
> > ...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/steam-runtime-tools-0/libvkbasalt.so`
> > ...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/libvkbasalt.so`
> > I am not using "`ENABLE_VKBASALT=1 %command%`" in Steam , instead I have directive "`export ENABLE_VKBASALT=1`" placed in the end of my `.profile` file.
> > My system is Kubuntu 20.10 , nVidia with nV drivers 460.32.03 , intel CPU
> > Hope this will help!
> 
> Where is this lbvkbasalt.so located?

just build the vkBasalt from source and take the libvkbasalt.so from src dir. For me it was `builddir/src/libvkbasalt.so` .

**Comment by JulioSordi** [comment]
> > > Hi,
> > > for me vkBasalt stopped working as well for combo **Witcher3 + Steam + Proton 5.13-5**
> > > I have fixed the issue with copying the "`libvkbasalt.so`" file into Steam's Soldier lib dirs.
> > > Just seek for a directory "`x86_64-linux-gnu`" in your steam apps directories and place the "libvkbasalt.so" file there.
> > > For me it was:
> > > ...`steamapps/common/SteamLinuxRuntime_soldier/soldier_0.20210105.2/files/lib/x86_64-linux-gnu/libvkbasalt.so`
> > > ...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/steam-runtime-tools-0/libvkbasalt.so`
> > > ...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/libvkbasalt.so`
> > > I am not using "`ENABLE_VKBASALT=1 %command%`" in Steam , instead I have directive "`export ENABLE_VKBASALT=1`" placed in the end of my `.profile` file.
> > > My system is Kubuntu 20.10 , nVidia with nV drivers 460.32.03 , intel CPU
> > > Hope this will help!
> > 
> > 
> > Where is this lbvkbasalt.so located?
> 
> just build the vkBasalt from source and take the libvkbasalt.so from src dir. For me it was `builddir/src/libvkbasalt.so` .

This builddir directory doesn't exist for me, i'm in Manjaro

**Comment by koubel** [comment]
> > > > Hi,
> > > > for me vkBasalt stopped working as well for combo **Witcher3 + Steam + Proton 5.13-5**
> > > > I have fixed the issue with copying the "`libvkbasalt.so`" file into Steam's Soldier lib dirs.
> > > > Just seek for a directory "`x86_64-linux-gnu`" in your steam apps directories and place the "libvkbasalt.so" file there.
> > > > For me it was:
> > > > ...`steamapps/common/SteamLinuxRuntime_soldier/soldier_0.20210105.2/files/lib/x86_64-linux-gnu/libvkbasalt.so`
> > > > ...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/steam-runtime-tools-0/libvkbasalt.so`
> > > > ...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/libvkbasalt.so`
> > > > I am not using "`ENABLE_VKBASALT=1 %command%`" in Steam , instead I have directive "`export ENABLE_VKBASALT=1`" placed in the end of my `.profile` file.
> > > > My system is Kubuntu 20.10 , nVidia with nV drivers 460.32.03 , intel CPU
> > > > Hope this will help!
> > > 
> > > 
> > > Where is this lbvkbasalt.so located?
> > 
> > 
> > just build the vkBasalt from source and take the libvkbasalt.so from src dir. For me it was `builddir/src/libvkbasalt.so` .
> 
> This builddir directory doesn't exist for me, i'm in Manjaro

I am not familiar with Manjaro, but I'd suppose it'll be somewhere in `/usr` or `/lib`. Try to find it like similar:

`find / -type f -name "libvkbasalt.so" 2>/dev/null`

**Comment by JulioSordi** [comment]
> > > > > Hi,
> > > > > for me vkBasalt stopped working as well for combo **Witcher3 + Steam + Proton 5.13-5**
> > > > > I have fixed the issue with copying the "`libvkbasalt.so`" file into Steam's Soldier lib dirs.
> > > > > Just seek for a directory "`x86_64-linux-gnu`" in your steam apps directories and place the "libvkbasalt.so" file there.
> > > > > For me it was:
> > > > > ...`steamapps/common/SteamLinuxRuntime_soldier/soldier_0.20210105.2/files/lib/x86_64-linux-gnu/libvkbasalt.so`
> > > > > ...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/steam-runtime-tools-0/libvkbasalt.so`
> > > > > ...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/libvkbasalt.so`
> > > > > I am not using "`ENABLE_VKBASALT=1 %command%`" in Steam , instead I have directive "`export ENABLE_VKBASALT=1`" placed in the end of my `.profile` file.
> > > > > My system is Kubuntu 20.10 , nVidia with nV drivers 460.32.03 , intel CPU
> > > > > Hope this will help!
> > > > 
> > > > 
> > > > Where is this lbvkbasalt.so located?
> > > 
> > > 
> > > just build the vkBasalt from source and take the libvkbasalt.so from src dir. For me it was `builddir/src/libvkbasalt.so` .
> > 
> > 
> > This builddir directory doesn't exist for me, i'm in Manjaro
> 
> I am not familiar with Manjaro, but I'd suppose it'll be somewhere in `/usr` or `/lib`. Try to find it like similar:
> 
> `find / -type f -name "libvkbasalt.so" 2>/dev/null`

I've just put the file there, still not working

**Comment by koubel** [comment]
> > > > > > Hi,
> > > > > > for me vkBasalt stopped working as well for combo **Witcher3 + Steam + Proton 5.13-5**
> > > > > > I have fixed the issue with copying the "`libvkbasalt.so`" file into Steam's Soldier lib dirs.
> > > > > > Just seek for a directory "`x86_64-linux-gnu`" in your steam apps directories and place the "libvkbasalt.so" file there.
> > > > > > For me it was:
> > > > > > ...`steamapps/common/SteamLinuxRuntime_soldier/soldier_0.20210105.2/files/lib/x86_64-linux-gnu/libvkbasalt.so`
> > > > > > ...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/steam-runtime-tools-0/libvkbasalt.so`
> > > > > > ...`steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/lib/x86_64-linux-gnu/libvkbasalt.so`
> > > > > > I am not using "`ENABLE_VKBASALT=1 %command%`" in Steam , instead I have directive "`export ENABLE_VKBASALT=1`" placed in the end of my `.profile` file.
> > > > > > My system is Kubuntu 20.10 , nVidia with nV drivers 460.32.03 , intel CPU
> > > > > > Hope this will help!
> > > > > 
> > > > > 
> > > > > Where is this lbvkbasalt.so located?
> > > > 
> > > > 
> > > > just build the vkBasalt from source and take the libvkbasalt.so from src dir. For me it was `builddir/src/libvkbasalt.so` .
> > > 
> > > 
> > > This builddir directory doesn't exist for me, i'm in Manjaro
> > 
> > 
> > I am not familiar with Manjaro, but I'd suppose it'll be somewhere in `/usr` or `/lib`. Try to find it like similar:
> > `find / -type f -name "libvkbasalt.so" 2>/dev/null`
> 
> I've just put the file there, still not working

then I don't know ...

Just a note: I am not a developer nor a support, just a happy and grateful user of vkBasalt, and as I had the same issue and been luckily able to solve it for me I posted my solution here.

**Comment by tonehrk** [comment]
I had the same issue. And I am Manjaro KDE user too. 
vkbasalt works correctely with vkcube but in steam and lutris is not working. 

My Solution was: Install **lib32-vkbasalt**... last update in AUR repos broke my lib32-vkbasalt library (didn't compile)... if you have same problem (cannot install lib32-vkbasalt by AUR)... just compile manually from src (remove AUR versions first). I did that and vkbasalt is working again.
