### ISSUE TITLE
vkBasalt err: no good config file

### ISSUE THREAD

**Issue by ErikSteiner** [DadSchoorse/vkBasalt#144]
With the config file from here (I didn't change something), I get the following error in vkBasalt.log:
`vkBasalt err:   no good config file`
https://raw.githubusercontent.com/DadSchoorse/vkBasalt/master/config/vkBasalt.conf

I installed vkbasalt via AUR on Manjaro, versio 0.3.2.4

**Comment by DadSchoorse** [comment]
Where is your config file located?

**Comment by ErikSteiner** [comment]
It turned out that the following entries in Lutris leads to this problem:
`VKBASALT_CONFIG_FILE` `/home/Erik/Nexus/Gaming/Mods/Star\ Citizen/vkBasalt.conf`
`VKBASALT_CONFIG_FILE` `"/home/Erik/Nexus/Gaming/Mods/Star Citizen/vkBasalt.conf"`

Correctly set like this:
`VKBASALT_CONFIG_FILE` `/home/Erik/Nexus/Gaming/Mods/Star Citizen/vkBasalt.conf`

So it was not an error by the file, but by the path.
