### ISSUE TITLE
[feature request] start vkbasalt in disabled state (enable later using key)

### ISSUE THREAD

**Issue by magiruuvelvet** [DadSchoorse/vkBasalt#153]
Since it is possible to toggle shaders on and off using a shortcut key, it would be nice to have an option to start with shaders disabled rather then enabled, to enable them later at some point.

What do you think?

**Comment by DadSchoorse** [comment]
There, 5800ca0354876e57552a53cc8865c6011a15e888

**Comment by magiruuvelvet** [comment]
That's nice, works like a charm :)

Thank you
