### ISSUE TITLE
SMAA makes text... aliased?

### ISSUE THREAD

**Issue by yagoplx** [DadSchoorse/vkBasalt#154]
I have tried tweaking the settings a bunch, but changing the threshold lower so that it catches more visible edges adds some ugly artifacting on text. Oddly enough, this artifacting does appear like aliasing.

Screenshots from Genshin Impact:
On:
![SMAA-on](https://user-images.githubusercontent.com/57966308/116945187-74fb0800-ac4d-11eb-90a4-922374c969a0.png)

Off:
![SMAA-off](https://user-images.githubusercontent.com/57966308/116945191-788e8f00-ac4d-11eb-8303-4eae710c3cb1.png)

**Comment by v1993** [comment]
This seems to be fixed by cranking up SMAA's quality settings all the way up and/or increasing smoothing factor a bit. It seems that sharpening picks up some patterns in output otherwise and makes intentionally sharp parts like text jagged.

**Comment by turol** [comment]
SMAA and FXAA don't really deal gracefully with already antialiased features like text. This is a known problem and the integration instructions say you should apply them before GUI rendering. Unfortunately with an injector like vkBasalt that is not an option so you either tweak the settings to minimize it or live with it...

**Comment by yagoplx** [comment]
So this is not vkbasalt's fault, thank you for the info
