### ISSUE TITLE
Doesn't work with Steam games on Proton 5.13+

### ISSUE THREAD

**Issue by guglovich** [DadSchoorse/vkBasalt#165]
Does not work in Steam games on versions above 5.13, including ProtonGE. Works from 3 to 5.0.10.  There is no problem when using PortProton. There is no problem with Vulkan games either.

**Comment by GoGoOtaku** [comment]
This is a potential duplicate of #152

**Comment by guglovich** [comment]
As I noticed the basic CAS works, but it is not clear from where the config is used or if this filter works without the config.

**Comment by guglovich** [comment]
I've moved all the shaders and configuration file from /usr and everything works without any further manipulation.
