### ISSUE TITLE
Dark vkCube

### ISSUE THREAD

**Issue by John-Gee** [DadSchoorse/vkBasalt#18]
I've just tried this on vkCube and it makes it very dark, is that expected?

On: https://i.imgur.com/E0Ztc8F.png
Off: https://i.imgur.com/lWYrdvF.png

I am using an AMD 580X on Mesa 19.3-dev.
No difference with llvm or aco.

Thanks!

**Comment by DadSchoorse** [comment]
This is definitely not expected. Does it only happen with vkcube or also in games?

**Comment by John-Gee** [comment]
Well I had not tried it with games yet, let's see.

I've just quickly tried with The Witcher 3 and I don't think it has the same issue, but the cube is very simple so it's also much easier to notice color variations.

**Comment by DadSchoorse** [comment]
This issue is very strange, because the shader does not modify big patches of one color at all. Also i have never seen vkcube so bright like you have without vkbasalt.

**Comment by John-Gee** [comment]
I've just reinstalled it in case, but it's the same.
Looking at google images I see variant shades some paler, some darker, not sure what it is actually supposed to look like.

**Comment by DadSchoorse** [comment]
Maybe yours uses an SRBG image... Can you give me the terminal output? And if you have it installed the output of vulkaninfo.

**Comment by rodrigo21** [comment]
I have the same issue. 
Also tested some games and it's working, but Unity engine games are crashing.

I have a AMD RX 550 and Mesa 19.2.1.

**Comment by fluffykittyrevenge** [comment]
Like mentioned in the other issue, I've been experiencing this as well.
With vkcube, RADV triggers the darkness and AMDVLK doesn't.
With Hitman 2, both work as expected.
With Mad Max, both RADV and AMDVLK trigger the darkenss (screenshot of it in #3).

I'm currently backing up some stuff before I reinstall Manjaro, but I'll post some output when I'm back up and running (btrfs issues :crying_cat_face:)

**Comment by John-Gee** [comment]
> Maybe yours uses an SRBG image... Can you give me the terminal output? And if you have it installed the output of vulkaninfo.

output: https://gist.github.com/John-Gee/8ee3fd89286b63deeee81d8aabd29b88

vulkaninfo: https://gist.github.com/John-Gee/2313ee78cbd779212e6e09b8033ebca2

I've tried some examples from Sacha Willem and don't see the issue there either.

**Comment by DadSchoorse** [comment]
Yeah it uses SRGB and the shader forces conversion to UNORM, that is the reason for the darker image. Also funny, according to the vulkaninfo this should not work at all.

**Comment by John-Gee** [comment]
Is supporting SRGB a big endeavor? Just curious, I don't need sharpening in vkcube :)

**Comment by DadSchoorse** [comment]
I do not know much about SRGB currently so we will see. @fluffykittyrevenge Mad Max might use SRGB too, causing the darkness.

**Comment by monterrr** [comment]
Running dead space using proton with d9vk and vkcube enabled makes the image very bright.

**Comment by DadSchoorse** [comment]
@monterrr probably an sRGB issue too, so you have to wait until I finish my rewrite.But you could give me the terminal output to make sure.

**Comment by monterrr** [comment]
Turns out it was d9vk fault!

**Comment by DadSchoorse** [comment]
@John-Gee @rodrigo21 @fluffykittyrevenge  please test the new build: #30

**Comment by John-Gee** [comment]
Yup it's not dark anymore, thank you!
