### ISSUE TITLE
Some games fail to start with ENABLE_VKBASALT=1 unless VKD3D_CONFIG=swapchain_legacy is present, on proton-experimental

### ISSUE THREAD

**Issue by Zeioth** [DadSchoorse/vkBasalt#198]
Due to a new implementation in VKD3D swapchain, some games will fail to start with vkbasalt unless VKD3D_CONFIG=swapchain_legacy is present. 

Issue only present on proton-experimental atm, but could potentially become a bigger issue if not addressed.

More info in the next threads:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/7683#note_1684730
https://github.com/ValveSoftware/Proton/issues/4450

**Comment by DadSchoorse** [comment]
Please retest with 08bb7e30feb0c287a31bab2231c5a53b52b04d94

**Comment by Zeioth** [comment]
@DadSchoorse it seems to work fine now without VKD3D_CONFIG=swapchain_legacy


## How did I tested

For the test I uninstalled vkbasalt, then compiled and installed as in the project's readme.md. As result MangoHud reports the game is running with vkbasalt after running it with ENABLE_VKBASALT=1 on proton-experimental, mesa stable, and Linux 6.1, and all seems ok.

I'm gonna keep testing with other versions of proton, but should be safe releasing a new version.

**Comment by Zeioth** [comment]
Hey thank you again. 
I've opened an AUR repo so anyone can test the master branch easily in the future https://aur.archlinux.org/packages/vkbasalt-git

Cheers.
