### ISSUE TITLE
0.3.2.7 game is crashing on startup

### ISSUE THREAD

**Issue by LyrixTheDj** [DadSchoorse/vkBasalt#199]
After updating (by compiling from source) **0.3.2.6** to **new release**, every game (dx9 x86 and dx11 x64)  is crashing on startup. Can't see any errors in log related to vkbasalt, all lines looks regular, only last is different: `Monitored process exited. Initial process has exited (return code: 1280) Exit with return code 1280`. But it definitely **0.3.2.7** release issue, after downgrade (recompiling) it games runs normally. I'm on Arch Linux: linux-zen-6.0.12/Mesa 22.2.3 amdgpu/Wine-GE-Proton7-34/DXVK 2.0/lutris. How to "debug" and provide more info about issue?

**Comment by DadSchoorse** [comment]
The new release should fix this, sorry for the regression.
