### ISSUE TITLE
Fatal error when trying to build vkBasalt (vulkan/vulkan.h: No such file or directory)

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [DadSchoorse/vkBasalt#2]
I get this error when trying to build vkBasalt:

> for i in src shader; do make -C $i; done
make[1]: Entering directory '/home/ahmed/Downloads/vkBasalt-master/src'
g++ compute_pipeline.cpp -o ../build/compute_pipeline.64.o -c  -O3 -fPIC  -m64
In file included from compute_pipeline.cpp:1:0:
compute_pipeline.hpp:9:10: **fatal error:** vulkan/vulkan.h: **No such file or directory**
 #include "vulkan/vulkan.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
makefile:22: recipe for target '../build/compute_pipeline.64.o' failed
make[1]: *** [../build/compute_pipeline.64.o] Error 1
make[1]: Leaving directory '/home/ahmed/Downloads/vkBasalt-master/src'
make[1]: Entering directory '/home/ahmed/Downloads/vkBasalt-master/shader'
glslangValidator -V cas.comp.glsl -o ../build/shader/cas.comp.spv
make[1]: glslangValidator: Command not found
makefile:11: recipe for target '../build/shader/cas.comp.spv' failed
make[1]: *** [../build/shader/cas.comp.spv] Error 127
make[1]: Leaving directory '/home/ahmed/Downloads/vkBasalt-master/shader'
makefile:4: recipe for target 'compile' failed
make: *** [compile] Error 2

**Comment by jarrard** [comment]
Yeah I get the same, 
My guess is you need to download lunar sdk and prepare the whole vulkan library path manually, not something most people will know or want to do. I've done it maybe once in the past and it was enough to make me say never again.

Can we just get a binary install release please?

**Comment by DadSchoorse** [comment]
There is a binary in the release. And yes, you need the Vulkan SDK, I have install it via the lunarg ppa

**Comment by DadSchoorse** [comment]
for the shader compile you need also glslang.

**Comment by jarrard** [comment]
ok so basically we just skip the make part and do make install.

**Comment by DadSchoorse** [comment]
Yes, that was my intention. It should not try to rebuild, else report it as a bug.

**Comment by ahmed-elsayed2017** [comment]
> Ok so basically we just skip the make part and do make install.

That worked, but it crashes every game that I try to run with it.

**Comment by DadSchoorse** [comment]
Do these files exist?
$(HOME)/.local/share/vkBasalt/libvkbasalt32.so
$(HOME)/.local/share/vkBasalt/libvkbasalt64.so
$(HOME)/.local/share/vkBasalt/shader/cas.comp.spv
$(HOME)/.local/share/vulkan/implicit_layer.d/vkBasalt32.json
$(HOME)/.local/share/vulkan/implicit_layer.d/vkBasalt64.json
and is library_path in the json files?

**Comment by DadSchoorse** [comment]
Yes it works with dxvk, i have tested witcher 3, skyrim and skyrim SE.

**Comment by ahmed-elsayed2017** [comment]
> Do these files exist?
> $(HOME)/.local/share/vkBasalt/libvkbasalt32.so
> $(HOME)/.local/share/vkBasalt/libvkbasalt64.so
> $(HOME)/.local/share/vkBasalt/shader/cas.comp.spv
> $(HOME)/.local/share/vulkan/implicit_layer.d/vkBasalt32.json
> $(HOME)/.local/share/vulkan/implicit_layer.d/vkBasalt64.json
> and what is library_path in the json files?

All these files exist, and the library path for both files

> "library_path": "/home/ahmed/.local/share/vkBasalt/libvkbasalt64.so"

> "library_path": "/home/ahmed/.local/share/vkBasalt/libvkbasalt32.so"

**Comment by DadSchoorse** [comment]
mhm, the install seems to have work, so this is a different problem.
What are your system infos?

**Comment by ahmed-elsayed2017** [comment]
> mhm, the install seems to have work, so this is a different problem.
> What are your system infos?

System Info:
CPU: Intel I5-4200M
GPU: AMD HD 8750M
Driver: Mesa 19.2.99 LLVM 10 (Padoka Unstable PPA)
DXVK: 1.4.3
OS: KDE neon 5.17 User Edition

**Comment by DadSchoorse** [comment]
probably related to #3 and an issue on all amd card. I need to rewrite a lot to fix this, so this could take some time.

**Comment by ahmed-elsayed2017** [comment]
> probably related to #3 and an issue on all amd card. I need to rewrite a lot to fix this, so this could take some time.

OK thanks. I will wait for the newer releases.

**Comment by DadSchoorse** [comment]
@ahmed-elsayed2017 I may have build that fixes it at #3 could you try it?

**Comment by ahmed-elsayed2017** [comment]
> @ahmed-elsayed2017 I may have build that fixes it at #3 could you try it?

I tested one game, and it works fine for me. The colors are so vivide. It is so beautiful. Thank you so much.

**Comment by ahmed-elsayed2017** [comment]
Games with bad anti-aliasing looks bad with vkBasalt. Is there any tool that can force anti-aliasing for Vulkan like SMAA, FXAA, or MSAA?

**Comment by DadSchoorse** [comment]
@ahmed-elsayed2017 SMAA is not going to happen, because it is to complex. MSAA might be possible and FXAA is definitely possible and I already did a little big of work for it, but no promises that it is going to happen.

**Comment by ahmed-elsayed2017** [comment]
> @ahmed-elsayed2017 SMAA is not going to happen, because it is to complex. MSAA might be possible and FXAA is definitely possible and I already did a little big of work for it, but no promises that it is going to happen.

FXAA is a wanted feature, because it doesn't affect performance as MSAA, and vkBasalt reverse all the bad effect of using FXAA, so it is a win win situation. I hope you consider it.

**Comment by turol** [comment]
I made a SMAA Vulkan demo: https://github.com/turol/smaaDemo/ . Also contains FXAA. Might make your job a bit easier.

**Comment by turol** [comment]
It's a tech demo. You build it, run it to see what happens and then look at the code to see how it does it. Also it's got image loading and debug modes so you can use it to cross-check your own implementation. And I've made some OpenGL and Vulkan -specific tweaks to the shaders so it's easier to make them work. The differing coordinate conventions are a pain.
