### ISSUE TITLE
Implement CMAA2

### ISSUE THREAD

**Issue by Kazevic** [DadSchoorse/vkBasalt#202]
Conservative Morphological Anti-Aliasing 2.0 (short CMAA2) is a form of anti-aliasing that aims to be safely implemented alongside other forms of anti-aliasing (like MSAA) and to handle aliasing better than FXAA and SMAA, mainly the UI elements, while maintaning a performance hit comparable to FXAA's.

Intel's (CMAA2 developer) article about it: https://www.intel.com/content/www/us/en/developer/articles/technical/conservative-morphological-anti-aliasing-20.html

Comparison (from left to right: source, FXAA, SMAA, CMAA2, CMAA2-ExtraSharpness): https://www.intel.com/content/dam/develop/external/us/en/images/conservative-morphological-anti-aliasing-two-fig12-785403.jpg

**Comment by charmandercha** [comment]
did you tried to use this shader?

https://github.com/LordOfLunacy/Insane-Shaders/blob/master/Shaders/CMAA_2.fx

**Comment by Kazevic** [comment]
> did you tried to use this shader?
> 
> https://github.com/LordOfLunacy/Insane-Shaders/blob/master/Shaders/CMAA_2.fx

Yes, but although it treats UI elements better than SMAA, it gives worse results than vkBasalt's SMAA. It is better than ReShade's SMAA though; even when I configured ReShade's SMAA so it would theoretically look the same as on vkBasalt, vkBasalt's implementation was better. I was hoping that DadSchoorse would implement this shader preconfigured for better quality than ReShade, just like he did with SMAA.

**Comment by charmandercha** [comment]
But Vkbasalt will no longer receiver updates

**Comment by Kazevic** [comment]
> But Vkbasalt will no longer receiver updates



> But Vkbasalt will no longer receiver updates

Thore are sad news, because vkBasalt does not work with GTA IV anymore and the addition of CMAA2 would blow anything else out of the water, but I understand, it must be hard to do that.

**Comment by charmandercha** [comment]
i never work with C++ before, but maybe it's easy?

CMAA2 is really superior than smaa or smaa + fxaa ?

**Comment by Kazevic** [comment]
It is MUCH better with text/HUD elements and looks considerably better overall. It blurs less than SMAA. See the comparison on my first comment.

**Comment by yupyup-cmyk** [comment]
> > did you tried to use this shader?
> > https://github.com/LordOfLunacy/Insane-Shaders/blob/master/Shaders/CMAA_2.fx
> 
> Yes, but although it treats UI elements better than SMAA, it gives worse results than vkBasalt's SMAA. It is better than ReShade's SMAA though; even when I configured ReShade's SMAA so it would theoretically look the same as on vkBasalt, vkBasalt's implementation was better. I was hoping that DadSchoorse would implement this shader preconfigured for better quality than ReShade, just like he did with SMAA.

I'm unable to get CMAA 2 even working on vkBasalt. How did you do it?

**Comment by Kazevic** [comment]
> > > did you tried to use this shader?
> > > https://github.com/LordOfLunacy/Insane-Shaders/blob/master/Shaders/CMAA_2.fx
> > 
> > 
> > Yes, but although it treats UI elements better than SMAA, it gives worse results than vkBasalt's SMAA. It is better than ReShade's SMAA though; even when I configured ReShade's SMAA so it would theoretically look the same as on vkBasalt, vkBasalt's implementation was better. I was hoping that DadSchoorse would implement this shader preconfigured for better quality than ReShade, just like he did with SMAA.
> 
> I'm unable to get CMAA 2 even working on vkBasalt. How did you do it?

Actually, I have used ReShade itself, not vkBasalt with ReShade shaders.

**Comment by aqxa1** [comment]
> I'm unable to get CMAA 2 even working on vkBasalt. How did you do it?

I don't think that implementation supports Vulkan (or any that I could find). Intel were planning to implement Vulkan support but they have since [abandoned CMAA2](https://github.com/GameTechDev/CMAA2).

**Comment by Kazevic** [comment]
That sucks. I will close my issue then. Thank you for informing us about it.

**Comment by aqxa1** [comment]
To be clear, it doesn't mean it would be impossible to port it to Vulkan, just that nobody has done it yet. But I wouldn't expect DadSchoorse to do it as the vkBasalt is in maintenance mode.
