### ISSUE TITLE
Can't find config file

### ISSUE THREAD

**Issue by ThePwnd** [DadSchoorse/vkBasalt#203]
I'm running on Pop_OS! 22.04 LTS, with Debian Steam, I'm trying to get vkBasalt working for Left 4 Dead 2.  I first tried installing vkBasalt from the apt package, but later removed the package and built vkBasalt using the instructions on the main GitHub page.  I believe I've tracked down all the dependencies, as I ran the ninja command and it completed compiling 37 scripts without errors.  The problem I'm having, is that I can't seem to tell if it's actually running.  I understand that the changes can be somewhat subtle to the untrained eye, but there doesn't appear to be any configuration file generated.  I checked all of the directories listed in the instructions, but there is no vkBasalt folder or .conf file in any of those locations.

I've tried creating vkBasalt.conf in my Left 4 Dead 2 directory, but the file is still empty after I launch the game and load a campaign.  I've also tried adding another launch parameter to Steam: `VKBASALT_CONFIG_FILE="/media/***/TheTinderBox/SteamLibrary/steamapps/common/Left 4 Dead 2/vkBasalt.conf"`.  Launching the game still doesn't populate the file.  I feel like I'm missing something obvious, but given the lack of an obvious vkBasalt directory after apparently completing the build and install, I feel confused.  What am I missing?  Let me know if you need any other info from me.

**Comment by Kazevic** [comment]
It most likely is on /etc/, have you already seen that directory? If it is not there, try to download the `vkbasalt.conf` file and put it into the folder of your game.

**Comment by ThePwnd** [comment]
Hey, thanks for following up with me!  I've actually figured out that this is apparently unique to Left 4 Dead 2.  I was able to get vkBasalt working on Rocket League by generating a config file with GOverlay and putting it in my Rocket League folder.

Left 4 Dead 2 is a native Linux game, and _seems_ to run on Vulkan, but a lot of people on Reddit have suggested that I need the 32-bit version.  I tried to build the 32-bit version from the build script instructions on the main page of the GitHub, but I get an error when the script is compiling 57/58.  I found this other issue here that seems to list the exact same problem (#172), and the author listed out several dependencies to install as the solution.  One of them, however - `linux-libc-dev:i386` - causes a strange error when I try to install it:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pop-desktop : Depends: build-essential but it is not going to be installed
               Recommends: io.elementary.sideload but it is not installable
               Recommends: pop-transition but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

I didn't reference the package `pop-desktop` anywhere.  All I ran was `sudo apt install linux-libc-dev:i386`.  I also already have `linux-libc-dev` installed, which I believed was going to clash with this 32-bit version (I swear I got an error complaining about a conflict earlier, but now I can't find the error anymore).  Trying to run `sudo apt remove linux-libc-dev` actually generates the same error as above.

Any ideas what all this means?

**Comment by Kazevic** [comment]
Is 32-bit vkBasalt not available on your package manager? Because it is on mine, so if it is, you probably can just install it there instead of running into issues with dependencies.

About the error, try to manually install the packages with unmet dependencies. I have found a similar question on Ask Ubuntu that was solved by doing that.

**Comment by ThePwnd** [comment]
It does not appear to be available in my package manager on Pop!_OS.  Running `sudo apt search vkBasalt` shows only the 64-bit vkBasalt package (already installed) and the GOverlay package (also installed).  Are you on Arch?  I have heard that it's available there.

About the error, I tried running `sudo apt install build-essential`, but that returns a message that it's already up to date with the latest version.  This error is very bizarre.  Just installing a 32-bit package for vkBasalt would be awesome.

Also, I was aware about the `-vulkan` launch parameter, but that has not yet gotten vkBasalt to work on L4D2.

**Comment by ThePwnd** [comment]
Aha!  So I managed to track down a manual download for the 32-bit package in question, and installed that way - https://packages.debian.org/sid/linux-libc-dev - Had to download and install the amd64 version to upgrade my existing instance first, then installed the i386 version.  I deleted and redownloaded the vkBasalt git repo, ran the 32-bit script with the configuration from the aforementioned issue #172, and now the build script completes successfully!

.... but vkBasalt still doesn't seem to be running in game =(  These are my current launch parameters: `ENABLE_VKBASALT=1 %command% -vulkan -novid`

**Comment by Kazevic** [comment]
I use Nobara (Fedora fork by GloriousEggroll, the developer of Proton-GE and Wine-GE).

I believe that the "%command" part should be at the end of the launch options, but take it with a grain of salt.

Is it really not enabled in game? Have you configured mangohud via GOverlay to make it so there is a indicator saying if vkBasalt is enabled/disabled?

**Comment by ThePwnd** [comment]
So the `%command%` part - at least from what I've read - should come after mangohud and vkBasalt, but before parameters like `-novid` and `-vulkan`.  More specifically, I'd also seen a few video tutorials on them that list the parameters in that order too.

Funny story about MangoHud... I haven't been able to get that one working on L4D2 either, and I have an issue open with their dev team as well a Reddit thread to try and sort that one out.

**Comment by Kazevic** [comment]
I found your thread on Reddit, let us continue the discussion there. We should only come back here if the issue is solved.

**Comment by ThePwnd** [comment]
For anyone else having this issue, the solution was to run L4D2 with [Gamescope](https://github.com/Plagman/gamescope).  This could be very simple, or potentially very complex if you're running Pop!_OS 22, like I am.  The same problem may also apply to Ubuntu 22, but I haven't tested there.  If you are one of these people, you'll need to either follow the steps in [this issue](https://github.com/Plagman/gamescope/issues/731), or just download [this .deb package](https://github.com/akdor1154/gamescope-pkg) for Gamescope on Pop!_OS.  It should be noted that I walked through the steps in the issue until the end, when I found the package, and I still had to install a few dependencies to get the package to install, following the helpful convention of `sudo apt install lib<dependencyName>-dev`.  I assume that the Gamescope .deb package takes care of most of the steps involved in the issue I've linked, but I can't confirm that.

Once Gamescope has been installed, (you can check by running `gamescope --help` in a terminal window) I had to restart my computer before I could get it to work in L4D2.  Once that's done, you can add it to your Steam launch parameters like so: `ENABLE_VKBASALT=1 gamescope -- %command% -vulkan`.  You can also include whatever additional Gamescope arguments for resolution, refresh rate, upscaling technology, etc. as you like.  It will start in windowed mode, and I had to press "Ctrl" + "Super/Windows" + "F" on my keyboard to toggle fullscreen mode.

Hope this helps someone!
