### ISSUE TITLE
FTBFS with new GCC 13

### ISSUE THREAD

**Issue by tim77** [DadSchoorse/vkBasalt#209]
### Description of Bug

Failed to build from source with new GCC 13.

### Attached Log

* [Full build log](https://kojipkgs.fedoraproject.org//work/tasks/9458/98669458/build.log)
* [Fedora Koji task](https://koji.fedoraproject.org/koji/taskinfo?taskID=98669458)

### Additional info

- OS: Fedora 38+
- Compiler: GCC 13.0.1

Porting to GCC 13: https://gcc.gnu.org/gcc-13/porting_to.html

---

The error itself with missing types look like in reshade modules itself. Please tell me if i should report this into reshade bugtracker, not vkBasalt.

**Comment by marxin** [comment]
Can be fixed with the following simple patch:

```patch
diff --git a/src/reshade/effect_token.hpp b/src/reshade/effect_token.hpp
index e85e2fa..f1b34a8 100644
--- a/src/reshade/effect_token.hpp
+++ b/src/reshade/effect_token.hpp
@@ -7,6 +7,7 @@
 
 #include <string>
 #include <vector>
+#include <cstdint>
 
 namespace reshadefx
 {
```

Please apply it if possible.

**Comment by parona-source** [comment]
Well seeing that reshade is its own repo then it would be fine to first fix it here and then afterwards look at upstreaming it. 

Either way upstream reshade and reshade version included here are not in sync.

Like the gcc-12 issue here was actually fixed two years in advance
https://github.com/DadSchoorse/vkBasalt/commit/d0d37e902360ad2fdd263ec4559c6413c52d95c7
https://github.com/crosire/reshade/commit/bef683b67c7eb7afe5d5dff8a7d5dfbd162fb1b0

**Comment by ranplayer** [comment]
I've encountered similar errors when trying to build it from AUR (**GCC 13.1.1**). Full build log: 
[vkbasalt.tar.gz](https://github.com/DadSchoorse/vkBasalt/files/11415984/vkbasalt.tar.gz)

An example of error line: `../src/reshade/effect_codegen.hpp:271:66: error: 'const struct reshadefx::struct_info' has no member named 'definition'`

**Comment by KyleGospo** [comment]
Can confirm this fixed the issue, but there's no git version of lib32-vkbasalt on the AUR. Could we get a new release so this is fixed for all packages?
