### ISSUE TITLE
feature req: per-app config file support

### ISSUE THREAD

**Issue by nergdron** [DadSchoorse/vkBasalt#231]
been playing with this a little bit, and I was thinking about writing a simple configuration GUI. however, I realized that before that would be actually useful, there's a feature I really really want: per-application config file support.

something like matching process names to `${SEARCH_PATH}/app.d/${NAME}.conf` should be sufficient, but really anything that lets you make configuration per-app would be sufficient.

Right now this is my biggest pain point with using vkbasalt in any real way, and once it's in place I think writing a simple config GUI would be a *lot* more useful.

**Comment by DadSchoorse** [comment]
vkBasalt first tries to load the config file from the working directory, which is effectively per-app for steam games. Or you can set the env variable for each app if you want to use a different location: https://github.com/DadSchoorse/vkBasalt#configure

**Comment by nergdron** [comment]
oh! I didn't realize there was working directory loading, I missed that. that's perfect actually, thanks!
