### ISSUE TITLE
AUR package link

### ISSUE THREAD

**Issue by John-Gee** [DadSchoorse/vkBasalt#24]
Hello,

I've created an AUR package for this and was suggested on reddit to have a link to it here.
Is this something you'd be interested in? If so I can create a PR on the readme.

Thank you!

**Comment by fosspill** [comment]
I assume this is the answer you are looking for:
https://github.com/DadSchoorse/vkBasalt/pull/20#issuecomment-545101852

**Comment by John-Gee** [comment]
Yup!
