### ISSUE TITLE
vkBasalt_DestroyDevice and vkBasalt_DestroyInstance leak memory

### ISSUE THREAD

**Issue by nicokoch** [DadSchoorse/vkBasalt#27]
The functions `vkBasalt_DestroyDevice` and `vkBasalt_DestroyInstance` do not call the next layer's `vkDestroy{Device,Instance}`functions, which means that the corresponding objects will never get freed.

**Comment by DadSchoorse** [comment]
I fixed the DestroyDevice memory leak with 585561a35fb88ca201ac3b3bb8ff03af1baa08ef , but if I try to call DestroyDevice it segfaults. I do not know why it does that, so any help would be appreciated.
