### ISSUE TITLE
The Evil Within, and Observation crash when vkBasalt is turned on

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [DadSchoorse/vkBasalt#29]
The Evil Within crashes when vkBasalt is turned on. I don't think that I need to use it with this game, because it is so dark already, but I thought that it worth mentioning.

**System Specs:**
CPU: Intel I5 4200M
GPU: AMD HD 8750M
Driver: Mesa 19.2.99 LLVM 10 (Padoka Unstable PPA)
Kernel: 5.3.8
OS: KDE neon 5.17 User Edition

**Comment by DadSchoorse** [comment]
What version of vkBasalt are you using? Could you give me the terminal output? And the output of vulkaninfo.

**Comment by ahmed-elsayed2017** [comment]
Version 0.0.5
[vulkaninfo.txt](https://github.com/DadSchoorse/vkBasalt/files/3790630/vulkaninfo.txt)
[The_Evil_Within.txt](https://github.com/DadSchoorse/vkBasalt/files/3790646/The_Evil_Within.txt)

**Comment by DadSchoorse** [comment]
Seems to be a problem related to presenting.
@doitsujin Do you know if id tech 5 also presents from compute?

**Comment by doitsujin** [comment]
The Evil Within is a D3D11 game, and DXVK presents only from the graphics queue, so no.

There seems to be a fairly severe memory management bug *somewhere*:
> free(): invalid next size (fast)

**Comment by ahmed-elsayed2017** [comment]
Observation also crashes when vkBasalt is turned on
[Observation.txt](https://github.com/DadSchoorse/vkBasalt/files/3792101/Observation.txt)

**Comment by ahmed-elsayed2017** [comment]
I was able to run The Evil Within without crashing after turning off SMAA from the game settings.
