### ISSUE TITLE
Testing needed on AMD

### ISSUE THREAD

**Issue by DadSchoorse** [DadSchoorse/vkBasalt#30]
vkBasalt now uses a graphics pipeline instead of a compute pipeline and accesses the image through a sampler. As always I am only able to test on NVIDIA, so any help testing the new build before I release it would be appreciated.

If something does not work, please attach the terminal output.

[vkBasalt.tar.gz](https://github.com/DadSchoorse/vkBasalt/files/3795205/vkBasalt.tar.gz)

**Comment by ahmed-elsayed2017** [comment]
I have tested it with the same game that was working with version 0.0.5, and it crashed during loading
[Darksiders3.txt](https://github.com/DadSchoorse/vkBasalt/files/3795079/Darksiders3.txt)

**Comment by DadSchoorse** [comment]
@ahmed-elsayed2017 seems like the shader makefile tried to rebuild. I worked around that now, the build in the first post has been updated.

**Comment by ahmed-elsayed2017** [comment]
> @ahmed-elsayed2017 seems like the shader makefile tried to rebuild. I worked around that now, the build in the first post has been updated.

That make it work as before, but the games that didn't work before still the same.

**Comment by fosspill** [comment]
I assume these changes are in master too. Just built master and have no issues on AMD.

**Comment by werman** [comment]
It crashes on 5700XT with latest AMDVLK 2019.Q3.6-1 running vkcube:

[amdvlk-vkcube.log](https://github.com/DadSchoorse/vkBasalt/files/3799089/amdvlk-vkcube.log)

It doesn't crash on RADV.

**Comment by DadSchoorse** [comment]
@werman try 
[vkBasalt.tar.gz](https://github.com/DadSchoorse/vkBasalt/files/3799127/vkBasalt.tar.gz)

**Comment by werman** [comment]
Now it works.

Also it works without visible issues on RADV in GTA V  and Path of Exile.

**Comment by DadSchoorse** [comment]
Latest master needs testing:
[vkBasalt.tar.gz](https://github.com/DadSchoorse/vkBasalt/files/3828246/vkBasalt.tar.gz)
Keep in mind that 32 bit now uses the `ENABLE_VKBASALT` variable, too.

**Comment by fosspill** [comment]
Anything specific you'd like us to test on AMD? Any specific configurations etc?

**Comment by fosspill** [comment]
Regardless, tested with the default config file and I cannot see any immediate issues.

**Comment by ahmed-elsayed2017** [comment]
It works fine, but the same games that wasn't working before still not working.

**Comment by DadSchoorse** [comment]
@fosspill please also test fxaa and cas simultaneously with:
`effects = fxaa:cas`

**Comment by fosspill** [comment]
Already did, no issues found other than that I didn't like the effect :)

**Comment by ahmed-elsayed2017** [comment]
Now, L.A.Noir doesn't work with the latest version you provided for testing.

**Comment by DadSchoorse** [comment]
did it work before?

**Comment by ahmed-elsayed2017** [comment]
> did it work before?

Yes.

**Comment by DadSchoorse** [comment]
Can you post the terminal output

**Comment by DadSchoorse** [comment]
@fosspill well fxaa is intended for old games without anti-aliasing.

**Comment by fosspill** [comment]
Ah it wasn't meant as a complaint! I can imagine places where it would be awesome.
Point was that both effects  seemed to render properly on AMD ;)

**Comment by ahmed-elsayed2017** [comment]
> Can you post the terminal output?

[LANoire.log](https://github.com/DadSchoorse/vkBasalt/files/3829041/LANoire.log)

The error message that appears when VKBasalt is turned on

![LANoire](https://user-images.githubusercontent.com/29783425/68550897-f6365d80-040f-11ea-9a22-2a8a662523e4.png)

**Comment by ahmed-elsayed2017** [comment]
> @fosspill please also test fxaa and cas simultaneously with:
> `effects = fxaa:cas`

I like the combination between the two. Any hope for OpenGL after the success with Vulkan?

**Comment by DadSchoorse** [comment]
> The error message that appears when VKBasalt is turned on

That does not make any sense at all. The error message points towards the reading of the config file. That part of the code should not have been changed...

**Comment by DadSchoorse** [comment]
I would appreciate some testing of the smaa Branch. Here is a build:
[vkBasalt.tar.gz](https://github.com/DadSchoorse/vkBasalt/files/3864499/vkBasalt.tar.gz)

**Comment by fosspill** [comment]
No issues to report with smaa:cas on AMD for me.

**Comment by ahmed-elsayed2017** [comment]
It woks ok with SMAA on, but the drop of performance is so noticeable. FXAA has no noticeable effect on performance.

**Comment by DadSchoorse** [comment]
@ahmed-elsayed2017 well that's why the F in FXAA stands for fast. Did you try any games that didn't work before?

**Comment by ahmed-elsayed2017** [comment]
L.A. Noire didn't work with the previous release, but it works fine with the latest release, but The Evil Within still crashes with every release, and I can't test Observation again, because I uninstalled it.

**Comment by DadSchoorse** [comment]
That's at least something.

**Comment by fosspill** [comment]
Ultra? And here I was going to request being able to increase the strength of it!

**Comment by DadSchoorse** [comment]
@fosspill Maybe it still possible to increase to the strength, I haven't look into the advanced settings.
The order of effects is critical, the effects will be run in order from left to right.

**Comment by fosspill** [comment]
Tested the newest release with cas:smaa:deband and it works well on amd!

**Comment by ahmed-elsayed2017** [comment]
> The Evil Within still crashes with every release.

This game doesn't crash when using AMDVLK + vkBasalt, but only crashes when using RADV.

**Comment by DistantThunder** [comment]
Using it with :
* RADV on Mesa 19.3.1
* AMDGPU on 5.4.7-zen1-1-zen
* vkBasalt 0.2.2-1

On Final Fantasy XIV. The game runs with effects applied, nothing to report atm.

**Comment by TheEvilSkeleton** [comment]
Using vkBasalt on Gentoo:
- Mesa 20
- LLVM 9.0.1
- AMDGPU drivers
- Linux 5.4.13-zen
- Latest vkBasalt
- Ryzen 5 1600
- RX 580 4GB
Playing GTA V using Proton in Steam; playing with above 60FPS no problem.

**Comment by DadSchoorse** [comment]
please open a separate issue for future problems.
