### ISSUE TITLE
CAS - minimum strength seems to be -1, not 0

### ISSUE THREAD

**Issue by aufkrawall** [DadSchoorse/vkBasalt#35]
off:
![off](https://user-images.githubusercontent.com/13510490/69157056-b1cc5100-0ae4-11ea-899d-0bc1d1360d0e.png)

0:
![0](https://user-images.githubusercontent.com/13510490/69157072-b8f35f00-0ae4-11ea-8d70-03a1db2c0331.png)

-1:
![-1](https://user-images.githubusercontent.com/13510490/69157101-c7417b00-0ae4-11ea-9022-a2a5c8bbd77a.png)

-1.5 (looks like -1 to me):
![-1 5](https://user-images.githubusercontent.com/13510490/69157124-d0cae300-0ae4-11ea-8d61-02c7bc18f89f.png)

Though -1 is still quite distinct. It would be nice if we could also have less aggressive sharpen for AA that is not that blurry.
I personally found ColorSharpen nice, as it's really cheap and doesn't seem to ring as much as Lumasharpen:
https://mega.nz/#!F4xUGSzQ!_rwnmSGuJ5K6ehYRtIIv92yKtCed9vadkdlOOjDS6a4
Found here:
https://reshade.me/forum/shader-presentation/5591-deblur#35214

**Comment by DadSchoorse** [comment]
So what is the issue? Does vkBasalt set the strength wrong? Or would you propose that the config file should mention negative values for the strength, too?

**Comment by aufkrawall** [comment]
Yeah, I think either it should propose -1 as the minimum or, which imho would be more logical, setting strength to 0 should match the current strength of -1.

**Comment by DadSchoorse** [comment]
Well, while it seems more logical, I think the strength settings should be the same as in ReShade or the NVIDIA-settings on windows.

**Comment by DadSchoorse** [comment]
6a186aba6ac2be253c48e3776310dc4027a78831

**Comment by DadSchoorse** [comment]
I am not sure if negative values still do something since f4a16649eec7fbabf835efebe5de3df2f7513e93.
But that commit makes CAS look much better at high strength settings

**Comment by aufkrawall** [comment]
-1 is still less sharp than 0, while it's generally more subtle than before. I think this is really a welcome change, as 1.0 still is extremely sharp.
