### ISSUE TITLE
Deband effect

### ISSUE THREAD

**Issue by Sporif** [DadSchoorse/vkBasalt#37]
Would it be possible to add a deband/dithering effect? Along with CAS and SMAA it's one of my main uses for ReShade and it would great to have it in vkBasalt.

**Comment by aufkrawall** [comment]
There is a GLSL shader for mpv, if that's any helpful.

**Comment by DadSchoorse** [comment]
@aufkrawall probably not, because of mpv LGPL license. But this seems possible, I might implement it if/when I have time.

**Comment by DadSchoorse** [comment]
I have implemented deband in the wip-deband branch. It is simply a port of the reshade shader to glsl so it should behave similar. The only problem is the random number the shader uses which I simply set to a constant value. Here is a build:
[vkBasalt.tar.gz](https://github.com/DadSchoorse/vkBasalt/files/3902315/vkBasalt.tar.gz)
Does the effect look like it should? I have never uses it before so I can't tell.

**Comment by Sporif** [comment]
I tested Witcher 3 and it looks very similar to ReShade with better performance. ReShade has a 5% perf hit while vkBasalt has a 2.5% hit,. I did set iterations to 1 since 4 hurts performance too much, and 1 is the default with ReShade anyways.

As for the random number maybe you could get an idea from this shader?
https://github.com/libretro/glsl-shaders/blob/master/misc/deband.glsl

**Comment by DadSchoorse** [comment]
I think I am not going to change the shader since 
https://github.com/DadSchoorse/vkBasalt/blob/7218d345acfd50975597477c96b347d6c89cab07/shader/deband.frag.glsl#L99
already is some what random and I see no reason to changes if it works as expected. 

I am going to merge that branch, or do you see something that needs to be changed?

**Comment by Sporif** [comment]
No I see no reason not to merge.

**Comment by turol** [comment]
The original shader uses `FrameCount` which makes the output vary across frames. I think this is to avoid "pixel-locking" artifacts.

**Comment by DadSchoorse** [comment]
@turol do you mean https://github.com/libretro/glsl-shaders/blob/master/misc/deband.glsl ?
The shader I am using is https://github.com/crosire/reshade-shaders/blob/master/Shaders/Deband.fx
But yeah, in someway we need a random mechanism, I just don't see a simple way to do it.

**Comment by ahmed-elsayed2017** [comment]
I am sorry! I have never heard about that effect before. What does it do exactly?
