### ISSUE TITLE
3D LUT shader for colour correction

### ISSUE THREAD

**Issue by aqxa1** [DadSchoorse/vkBasalt#38]
Useful in particular for playing sRGB content on wide gamut monitors, which are becoming more and more common. You could also use it for any type of colour manipulation (e.g to intentionally over/under saturate), by generating your own 3D LUT.

DisplayCAL has a Reshade shader that implements this: https://sourceforge.net/p/dispcalgui/code/HEAD/tree/trunk/DisplayCAL/ColorLookupTable.fx, which I use with Wine + DXVK effectively (but it would be nice for native games, and games that don't play nice with Reshade).

**Comment by DadSchoorse** [comment]
So by 3D LUT what file format do you mean? Some sort of `.png` or these `.cube` that image manipulation software uses? On an other note that shader you linked uses 2d images internally which seems weird for a 3d LUT.

**Comment by aqxa1** [comment]
@DadSchoorse PNG files, yes. 

I don't have a deep understanding of how it works, but I believe you use several 2D textures but treat them as 3D (presumably R, G, B + Alpha):

See this link:
https://threejsfundamentals.org/threejs/lessons/threejs-post-processing-3dlut.html

>WebGL1 doesn't support 3D textures so we'll use 4x2 2D texture and treat it as a 3D texture inside a custom shader where each slice of the cube is spread out horizontally across the texture.

And another example implementation, this time as a slang shader in Retroarch: https://github.com/libretro/slang-shaders/blob/master/crt/shaders/guest/lut/lut.slang

You can also see some example LUTs in that repo, simulating the colours of a ![Sony Triniton CRT](https://github.com/libretro/slang-shaders/blob/master/crt/shaders/guest/lut/sony_trinitron1.png)

It would be nice to support several different sizes for the LUT png (DisplayCAL can export to 16x16x16, 32x32x32, and 64x64x64 colours), although 64x64x64 would be enough to begin with.

Thanks

**Comment by DadSchoorse** [comment]
I have implemented a 3D LUT shader in the wip-lut branch. It supports PNG like [that one](https://github.com/libretro/slang-shaders/blob/master/crt/shaders/guest/lut/sony_trinitron1.png) and .CUBE files. To use it, set `effects = lut` and `lutFile = /path/to/lut/without/spaces` in the config.
Here's a build:
[vkBasalt.tar.gz](https://github.com/DadSchoorse/vkBasalt/files/3932584/vkBasalt.tar.gz)
Testing would be appreciated.

**Comment by aqxa1** [comment]
Thanks! Just tested, and it works as expected so far (with native Vulkan and D9VK/DXVK). I've only tested DisplayCAL generated LUTs (which are the most important for me) so I'll try and test some others.

**Comment by aqxa1** [comment]
CUBE LUTs also look to be working well.

The only issue I've had so far was one particular .png LUT causing a strong yellow tint with Rise of the Tomb Raider (and only that particular game). There's a decent chance that the LUT itself is the problem, although I've been using the LUT with ReShade for a while and it's the first time I've had an issue with it. A new CUBE LUT with similar settings doesn't have the issue, for the record.

I'll try and figure out if it's the LUT at fault, rather than your code.

**Comment by DadSchoorse** [comment]
Can you give me the yellow LUT?

**Comment by aqxa1** [comment]
@DadSchoorse Sure. 

[lut-dcip3](https://user-images.githubusercontent.com/20884643/70371730-0831f000-192b-11ea-955f-2e0958c5e5dd.png)

It's not hugely noticeable but it should be visible when comparing screenshots. Here's a comparison to show what I mean:

No LUT ![No LUT](https://i.imgur.com/NdvhTr1.jpg)

PNG LUT ![PNG LUT](https://i.imgur.com/7rhlYV2.jpg)

Cube LUT ![Cube LUT](https://i.imgur.com/VvdGtf0.jpg)

These are intended to be run on a wide gamut monitor, but the yellow tint should be noticeable with standard gamut monitors as well. I used different gamma settings on the Cube LUT, so ignore the brightness difference.

**Comment by DadSchoorse** [comment]
It does not seem to cause a yellow tint in my testing:
![489830_20191207101448_1](https://user-images.githubusercontent.com/49841484/70372066-c2e5d200-18da-11ea-9084-e7f98d82cfc8.png)
This is without the LUT:
![489830_20191206161544_1](https://user-images.githubusercontent.com/49841484/70372071-d4c77500-18da-11ea-941a-da7ab4c67de5.png)

**Comment by aqxa1** [comment]
I think it's just game specific. I also tested generating a CUBE lut with the same settings as the older PNG and it does exhibit the same problem. It might be those particular settings cause problems in only certain games.

I can most likely just work around it on my end by choosing different settings.

**Comment by DadSchoorse** [comment]
Okay then I am going to merge the branch and close this issue.

**Comment by aqxa1** [comment]
Thanks. Just figured out it was the "Tone Curve" setting in DisplayCAL causing the problem, for the record (use Rec. 1886 instead of Gamma 2.2, and manually choose a 2.2 gamma after that).

**Comment by HexHyte** [comment]
> Thanks. Just figured out it was the "Tone Curve" setting in DisplayCAL causing the problem, for the record (use Rec. 1886 instead of Gamma 2.2, and manually choose a 2.2 gamma after that).

Sorry for reviving this old topic but i wanted to ask you if with "use Rec. 1886 instead of Gamma 2.2" you mean to do the calibration with this setting and then changing it to Gamma 2.2 when creating the 3D LUT?

**Comment by aqxa1** [comment]
@HexHyte Sorry I missed your comment. I wish I'd made more detailed notes, because I'm honestly not sure. 
The default setting would be to calibrate with a "Gamma 2.2" tone curve, then map that to a 3D LUT with source colourspace "Rec709" and tone curve "Rec 1886". I'll add that I haven't seen any obvious issues with recent LUTs I've made with close to the default settings, but I haven't looked at Rise of the Tomb Raider recently.

As a side note, I'll add that the flatpak version as of today doesn't include all available source colourspaces (such as Rec 709 which you want for standard sRGB content). A workaround is to extract the binaries of the latest argyllcms somewhere, and load them with displaycal. See [here](https://blog.checkyo.tech/2022/06/20/steam-deck-display-calibration/)
