### ISSUE TITLE
Please respect FHS by default

### ISSUE THREAD

**Issue by eclipseo** [DadSchoorse/vkBasalt#44]
Per FHS spec, binaries should go in /usr/lib(32) and /usr/lib64. /usr/share should not contain any binary.

**Comment by DadSchoorse** [comment]
I mean, vkBasalt installs into `~/.local/share`, not `/usr/share`. The install script should be rewritten anyway.

**Comment by ionenwks** [comment]
On a side-note, when the library is installed in /usr/lib(32) and /usr/lib64, vulkan can auto-detect the right one to use with a single .json file (assuming system is setup properly anyway), this may be more suitable if doing a system-wide install (personally also set it as an explicit_layer.d and removed the environment variable, prefer to use VK_INSTANCE_LAYERS to select layers to load).

That aside, packagers can deal with system-wide installations for now, users generally shouldn't do that. Eventually be nice to have adopt a proper build system, but I'd argue there's no rush.

**Comment by DadSchoorse** [comment]
@ionenwks I have been thinking about the explicit vs implicit layer, too. I am not quite sure, what would be easier for end users. Making vkBasalt explicit would have the benefit, that the effects get not applied to the steam overlay and the steam screenshots include the effects.

**Comment by tgurr** [comment]
I'd also love to see the build system overhauled to respect FHS and I'd like to add a request that `vkBasalt.conf` should also be moved. Out of `/usr/share` where it gets overwritten on package updates/reinstalls to maybe `/etc` which according to the README.md currently isn't among the search paths of vkBasalt.

**Comment by ionenwks** [comment]
To be fair I think the /usr/share config file should be seen as the fallback if nothing else is found (aka, it's the example/default file that a user would copy and edit in his home directory or a per-game basis, and not the file that you should edit). Although if really want system-wide configuration, it's the only place it looks for that.

**Comment by tgurr** [comment]
Other packages usually install their example file into the documentation under /usr/share/doc/pkgname, and their defaults to /etc which distributions could customize, especially if there are actual settings that get applied and and it's not just a file with only comments/comment out variables. Many distributions offer a way to show e.g. a diff for config files installed under /etc so on package upgrades the user can review the changes while in /usr/share the files just get overwritten without any notice.

I've explained my reasoning for being able to ship some defaults in the second paragraph of https://github.com/DadSchoorse/vkBasalt/issues/59 e.g. to ship sane defaults for reshade{Include,Texture}Path if distributed and installed with vkbasalt or an additional package so the user wouldn't have to figure that ones out. That makes only sense if the configuration files are stacked/merged on runtime though, else the users would have to set the paths again in their own configs.

**Comment by DadSchoorse** [comment]
I will no longer provide binaries and the new build system should install in the right location.
53609b0414184f0da22aef7b69a775c643afdd3f also added support for config files in `/etc`.

**Comment by DadSchoorse** [comment]
Closing due to old age + I think vkBasalt is now pretty FHS compliant.
