### ISSUE TITLE
TAA? and possible for OpenGL also?

### ISSUE THREAD

**Issue by jarrard** [DadSchoorse/vkBasalt#47]
Just wondering if something like this could be implemented in OGL? 

Currently I have several OGL games that only have FXAA as a option and its terrible!

Also wondering if TAA and HQ TAA options are possible with vkbasalt.

PS. I do not know of any projects doing a similar thing for OpenGL, at least that's compatible with both amd and nvidia hardware.

**Comment by DadSchoorse** [comment]
1. So TAA is not possible because it needs camera information and vkBasalt has no way to get it.
2. OpenGl is more garbage than graphics api. With Vulkan I can use the layer system which is great for this use case. OpenGl does not have anything like that. So no.

**Comment by jarrard** [comment]
well thats a real shame. :(
