### ISSUE TITLE
Request for versioned release tarballs

### ISSUE THREAD

**Issue by tgurr** [DadSchoorse/vkBasalt#58]
It would be helpful for distribution packagers to have the version in the actual release tarball filename. Right now fetching any version would result in just `vkBasalt.tar.gz`. Please consider naming release tarballs e.g. `vkBasalt-0.3.0.tar.gz`

EDIT: going with it the top level directory in the tarball should of course also be renamed from just `vkBasalt` to `vkBasalt-0.3.0` then.

**Comment by pchome** [comment]
1. distribution packagers should build packages for their distribution from sources (AFAIK)
2. check the url(s), there are "versions" (actually tags, but anyway), they are usually have the same format across versions (unless someone will decide to add some random **frogs** there)

**Comment by DadSchoorse** [comment]
> (unless someone will decide to add some random frogs there)

![grafik](https://user-images.githubusercontent.com/49841484/73976605-f53a9c80-4928-11ea-858b-66149083657e.png)

**Comment by tgurr** [comment]
> 1. distribution packagers should build packages for their distribution from sources (AFAIK)

We still do that anyways, but ...

> 2. check the url(s), there are "versions" (actually tags, but anyway), they are usually have the same format across versions (unless someone will decide to add some random **frogs** there)

... the problem is only the release tarball contains all git submodules already included, when building from a tag we also have to take care of additionally fetching the submodules and taking care of getting the correct revisions of them on every single bump, which is a real pain.

**Comment by pchome** [comment]
In my custom Gentoo overlay I solved this issue by packaging [Reshade FX](https://github.com/pchome/vulkan-gentoo-overlay/blob/master/dev-util/reshade-fx/reshade-fx-4.5.3-r1.ebuild).
`$ equery f reshade-fx`
```
 * Searching for reshade-fx ...
 * Contents of dev-util/reshade-fx-4.5.3-r1:
/usr
/usr/include
/usr/include/reshade
/usr/include/reshade/effect_codegen.hpp
/usr/include/reshade/effect_expression.hpp
/usr/include/reshade/effect_lexer.hpp
/usr/include/reshade/effect_module.hpp
/usr/include/reshade/effect_parser.hpp
/usr/include/reshade/effect_preprocessor.hpp
/usr/include/reshade/effect_symbol_table.hpp
/usr/include/reshade/effect_token.hpp
/usr/lib
/usr/lib/libreshade-fx.a
/usr/lib64
/usr/lib64/libreshade-fx.a
/usr/share
/usr/share/doc
/usr/share/doc/reshade-fx-4.5.3-r1
/usr/share/doc/reshade-fx-4.5.3-r1/README.md.bz2
```
Requires [some patching](https://github.com/pchome/vulkan-gentoo-overlay/blob/master/media-libs/vkbasalt/vkbasalt-0.3.0.ebuild), but works.

**Comment by tgurr** [comment]
@pchome thanks for the info, I'll have a look. It would be nice if you would contribute your meson work upstream, I couldn't find any open pull request in this regard.

**Comment by pchome** [comment]
#19
Same for reshadefx, even if meson can produce [Visual Studio projects](https://mesonbuild.com/Using-with-Visual-Studio.html), author already have working build system and unlikely will want any changes.

So no reason to bother them.

**Comment by tgurr** [comment]
Oh well that's a bummer, cause right now the makefile from vkBasalt is quite tedious always trying to build 32 and 64 bit without at least having different make targets so the meson approach would definitly have improved things.

**Comment by mcoffin** [comment]
@tgurr if you just want a simple meson setup for `vkBasalt`, I have a simple one in my [`meson-build` branch](https://github.com/mcoffin/vkBasalt/tree/meson-build).

**Comment by Calinou** [comment]
Another reason for uploading versioned release tarballs (instead of GitHub's automatically generated tarballs) is that their checksums will be stable over time. There's no guarantee a GitHub-generated tarball's checksum won't change over time, which is problematic for install scripts.

**Comment by stephanlachnit** [comment]
> Same for reshadefx, even if meson can produce Visual Studio projects, author already have working build system and unlikely will want any changes.

The author could still accept an additional build system for non-Windows users. I can give it a shot.

**Comment by DadSchoorse** [comment]
There are now release tarball - sadly without frogs. :frog:
