### ISSUE TITLE
Can't build after tag v0.3.0

### ISSUE THREAD

**Issue by EduFrazao** [DadSchoorse/vkBasalt#63]
Hi. I can't build vkBasalt with version >= v0.3.0.
I got this error:

`
mkdir -p ../build
c++ effect_fxaa.cpp -o ../build/effect_fxaa.64.o -c  -O3 -fPIC -Wall -Wextra -Wno-unused-parameter -std=c++2a -I../reshade/deps/spirv/include/spirv/unified1 -m64
In file included from effect_fxaa.cpp:12:
sampler.hpp:14:10: fatal error: ../reshade/source/effect_module.hpp: No such file or directory
   14 | #include "../reshade/source/effect_module.hpp"

`
There is something missing?

**Comment by DadSchoorse** [comment]
You are probably missing the reshade sub module. Try running `git submodule update --init` .

**Comment by EduFrazao** [comment]
Hi @DadSchoorse . Thanks for answer. You are right, reshade submodule was missing, but now I got a different error:

../reshade/source/effect_codegen_spirv.cpp:14:10: fatal error: spirv.hpp: No such file or directory
   14 | #include <spirv.hpp>

I have spirv-tools and headers installed.

**Comment by EduFrazao** [comment]
@DadSchoorse please, ignore my last post. After deleting and clone everything again it works.
Thanks for your time.
