### ISSUE TITLE
vkBasalt doesn't read config from `~/.config/vkBasalt/vkBasalt.conf`

### ISSUE THREAD

**Issue by axredneck** [DadSchoorse/vkBasalt#65]
Readme says it should.
Moving the config to `~/.local/share/vkBasalt/vkBasalt.conf` works around the issue.

**Comment by DadSchoorse** [comment]
I can't reproduce the issue. Are you sure that you use the latest version of vkBasalt? Do you have a custom `XDG_CONFIG_HOME` ?

**Comment by axredneck** [comment]
My bad, i forgot to update vkBasalt to 0.3.
