### ISSUE TITLE
Darksiders Genesis crashes when using vkBasalt v. 0.3.1

### ISSUE THREAD

**Issue by Ahmed-E-86** [DadSchoorse/vkBasalt#68]
Darksiders Genesis crashes when using vkBasalt version 0.3.1, it worked fine when I was using vkBasalt version 0.3.0.

Here is a log from the terminal: [log.txt](https://github.com/DadSchoorse/vkBasalt/files/4335554/log.txt)

### System info:
**CPU:** Intel Core I5 4200M
**GPU:** AMD Radeon HD 8750M
**OS:** Kubuntu 19.10 - KDE Plasma 5.18.3
**Kernel:** 5.3.0-40
WINE version 5.4 staging
vkBasalt version 0.3.1

**Comment by DadSchoorse** [comment]
Please create a log file with `VKBASALT_LOG_LEVEL=trace`. [More info](https://github.com/DadSchoorse/vkBasalt#debug-output)
Also, could you try if mangohud works fine? Then I would know that it's not input related.

**Comment by Ahmed-E-86** [comment]
I tried the same game today, and it didn't crash with version 0.3.1. I don't know if the kernel update that I installed today is the reason for that or not, but I didn't do anything else that could magically fixed this issue. Anyway, this issue is fixed. Cheers!
