### ISSUE TITLE
black screen with latest vkbasalt

### ISSUE THREAD

**Issue by zany130** [DadSchoorse/vkBasalt#69]
version 0.3.1 broke vkBasalt for me when i run 
```  ENABLE_VKBASALT=1 vkcube ```
I get a black screen this the output I get
[gist](https://gist.github.com/zany130/fef0873f193bbb5f205668002670fe60)

**Comment by DadSchoorse** [comment]
Nothing unusually in that log. Does the same happen with only `cas`? Maybe a shader doesn't work anymore.

**Comment by DadSchoorse** [comment]
it's `HighPassSharpen`, `GaussianBlur` and `Clarity` that are broken, seems strange. I might talk to crosire about that.

**Comment by DadSchoorse** [comment]
If you replace `COLOR` with `SV_Target` they work again. So that is something @crosire needs to solve.

**Comment by zany130** [comment]
oh ok in the meantime I reverted to 3.0.0 which works for me

**Comment by crosire** [comment]
And here I had hoped to kill support for those legacy names. But no, of course there had to be shaders who use them. Reintroduced here to make them work: https://github.com/crosire/reshade/commit/76516057aaa83794f6ba7cf4bcd496655baa546e.
