### ISSUE TITLE
Quick and Dirty UI

### ISSUE THREAD

**Issue by Rogue-Factor** [DadSchoorse/vkBasalt#71]
Sorry, I usually lurk and don't post much on GitHub if at all, so I wasn't sure if this was the correct format. Feel free to delete if this is wrong.

Looking at how this works (To much of my limited knowledge) is there a way for an outside program to send a command to vkBasalt in the form of a reset/refresh of the injection? I'm asking because if there is, one could write a simple script (or slightly more complex GUI) that interacts with said command while allowing easy editing of configuration files on the fly even while ingame through sliders and bool toggles.

That way a simple UI could be made that could allow you to keep working on the more important parts of vkBasalt, while increasing adoption rates for those less likely to edit .conf files manually and probably help speed up testing of shaders. Since it only sends a reset/refresh command, that project could be dropped later on when vkBasalt gains it's own GUI without actually being a detriment the main project.

**Comment by DadSchoorse** [comment]
> is there a way for an outside program to send a command to vkBasalt in the form of a reset/refresh of the injection?

No, currently it's very simple with all of the setup done early so that the runtime overhead is as low as possible. This may have been the wrong decision. I could probably change it, but I lost interest in this project, so I will not work on it, at least for now.

**Comment by Rogue-Factor** [comment]
Alright, thanks for the response. Well I suppose that if such a project might interest you again, I may be able to help at some point in the future.
