### ISSUE TITLE
Found a GUI for vkBasalt

### ISSUE THREAD

**Issue by TheEvilSkeleton** [DadSchoorse/vkBasalt#72]
Hello, I have found an awesome project made by [benjamimgois](https://github.com/benjamimgois), which brings a GUI to vkBasalt. In case you want to, you can add it in your README.

Here's the link: https://github.com/benjamimgois/goverlay

In case you are wondering, this is not advertisement. I am not associated with him in any way, shape or form. I independently decided to create this issue because I support both of your projects.

**Comment by gplastic** [comment]
Interesting.
