### ISSUE TITLE
vkBasalt runtime dependency on libstdc++.so.6

### ISSUE THREAD

**Issue by WinterSnowfall** [DadSchoorse/vkBasalt#75]
First off, I'd like to thank you for this little nifty piece of work. I'm mostly using it to enhance older games I'm running with DXVK by applying FXAA or SMAA, and it works great so far!

That being said, I'm a Debian/Ubuntu user and I've had a hard time getting it to run because of its dependency on libstdc++.so.6. Just to be clear, I'm picking the neat and easy way of getting the binary package and make install-ing.

The problem is that whenever I try to run anything I get:

`ERROR: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by /home/snowfall/.local/share/vkBasalt/libvkbasalt64.so)`

on Ubuntu 18.04/Mint 19 (the current LTS). This is because it only ships with gcc-8 and somewhat outdated libraries. I've worked around it by getting a newer version of the lib and using LD_LIBRARY_PATH for now.

I understand the need for gcc-9 & libs to be there for compilation, but even during runtime?

I'm hardly the person to preach or an expert, since I haven't written any C/C++ code in about, oh, 15 years, so there may be things I'm not aware of when I'm saying this, but have you considered statically linking with `-static-libstdc++` ?

**Comment by WinterSnowfall** [comment]
... just to clarify, I do have **libstdc++.so.6** installed, but:

```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by ismaelbonato** [comment]
I've installed this ppa https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

I installed gcc-9 and g++9 packet.

**Comment by DadSchoorse** [comment]
Yeah, I know that this is an issue, but I don't really know how to solve it.
vkBasalt needs c++2a, also because reshade needs it, so I need to build the release package with gcc>=9.
One solution would be to static link everything except libx11, but I don't think that's possible with gcc.

**Comment by DadSchoorse** [comment]
please try this build on 18.04 without the ppa
[vkBasalt.tar.gz](https://github.com/DadSchoorse/vkBasalt/files/4497311/vkBasalt.tar.gz)
It was made using `-static-libstdc++ -static-libgcc`, I hope that's enough.

**Comment by Monsterovich** [comment]
> please try this build on 18.04 without the ppa (or any other effected distro).
> [vkBasalt.tar.gz](https://github.com/DadSchoorse/vkBasalt/files/4497311/vkBasalt.tar.gz)
> It was made using `-static-libstdc++ -static-libgcc`, I hope that's enough.

Thank you. It works.

**Comment by WinterSnowfall** [comment]
> It was made using `-static-libstdc++ -static-libgcc`, I hope that's enough.

Thanks! It does indeed work on 18.04 without any tinkering and I expect on any other distro with older libraries. I know it increases the file size, but I'm hoping it's something you'll do for regular binary packages from now on :).

**Comment by DadSchoorse** [comment]
I will no longer provide binaries so this issue is resolved.
