### ISSUE TITLE
Running make seems to fail (Ubuntu 20.04)

### ISSUE THREAD

**Issue by GottaSlay** [DadSchoorse/vkBasalt#76]
Here's the output of running `make`:

> slay@slay-System-Product-Name:~/vkBasalt$ make
for i in src shader; do make -C $i; done
make[1]: Entering directory '/home/slay/vkBasalt/src'
mkdir -p ../build
g++ effect_fxaa.cpp -o ../build/effect_fxaa.64.o -c  -O3 -Wall -Wextra -Wno-unused-parameter -fPIC -std=c++2a -I../reshade/deps/spirv/include/spirv/unified1 -I../include -m64
make[1]: g++: Command not found
make[1]: *** [makefile:28: ../build/effect_fxaa.64.o] Error 127
make[1]: Leaving directory '/home/slay/vkBasalt/src'
make[1]: Entering directory '/home/slay/vkBasalt/shader'
mkdir -p ../build/tmp
mkdir -p ../build/shader
glslangValidator -V fxaa.frag.glsl -o ../build/tmp/fxaa.frag.spv
make[1]: glslangValidator: Command not found
make[1]: *** [makefile:19: ../build/tmp/fxaa.frag.spv] Error 127
make[1]: Leaving directory '/home/slay/vkBasalt/shader'
make: *** [makefile:9: compile] Error 2

**Comment by nickgirga** [comment]
> "glslangValidator: Command not found"

You need glslang installed. I think Ubuntu 20.04 doesn't have a package with that specific name, but glslang-dev _should_ work. If not, you can always still download binaries or the source from https://github.com/KhronosGroup/glslang/releases

Also, just in case you just didn't see it in the README, all releases of vkBasalt come packaged with compiled binaries. You can simply execute "make install" to just install it.

**Comment by evenfrost** [comment]
It's
```bash
sudo apt install glslang-tools
```

**Comment by evenfrost** [comment]
Also, for the next step `spirv-headers` package needs to be installed:
```bash
sudo apt install spirv-headers
```
