### ISSUE TITLE
Building with any gcc optimization causes freeze or crash

### ISSUE THREAD

**Issue by Sporif** [DadSchoorse/vkBasalt#8]
`-O3` and `-O2`  cause a freeze that requires sshing in to kill vkcube. `-O1` and `-Os` cause a segmentation fault. But no optimizations works fine. The builds on the release page also work without issues. 

Maybe the cause is the gcc version (assuming you built it with `-O3`)? I'm using gcc 9.2

**Comment by fluffykittyrevenge** [comment]
Nice fine.  Removed -O3 from src/makefile and that got my build working for vkcube with RADV and AMDVLK.

Also played a few minutes of Hitman 2 with RADV and AMDVLK and can tell that it was working since the colors seem to be more vibrant.
