### ISSUE TITLE
New version with meson build system

### ISSUE THREAD

**Issue by FireBurn** [DadSchoorse/vkBasalt#84]
Hi

Just wondering if you'd mind cutting a new release with the meson build system, I've made a live ebuild for gentoo but I know some folks would prefer a release and meson works great

Cheers

Mike

**Comment by stephanlachnit** [comment]
+1 from me, once a new tag is up I can start creating a Debian package.

**Comment by DadSchoorse** [comment]
[Version 0.3.2](https://github.com/DadSchoorse/vkBasalt/releases/tag/v0.3.2) has been released. Sorry for the delay, I had some issue in the last time.

**Comment by stephanlachnit** [comment]
Thanks! Btw I think with this release you can close #44 and #58.

**Comment by FireBurn** [comment]
Thanks, thats it now in my overlay. I'll tidy it up and see if portage is interested in it

It wasn't working at first but I noticed 0.3.2.1 was released afterwords - thanks again
