### ISSUE TITLE
vkBasalt err: no good config file

### ISSUE THREAD

**Issue by vinifmor** [DadSchoorse/vkBasalt#85]
Hello,

I've been trying to use vkBasalt with some games, but it seems not to be working. I ran vkCube (`VK_LOADER_DEBUG=all ENABLE_VKBASALT=1 vkcube`) to see the logs and it seems something related to the config file:

`vkBasalt err:   no good config file`

My config file (`~/.config/vkBasalt.conf`):
```
effects = fxaa:cas
depthCapture = off
casSharpness = 0.4
fxaaQualitySubpix = 0.75
fxaaQualityEdgeThreshold = 0.125
fxaaQualityEdgeThresholdMin = 0.0312
```

My specs:
S.O: Manjaro Linux 20
Kernel: 5.4.43
Driver: Nvidia 440.82
GPU: GTX 970 4GB

I'm attaching the full logs here -> [vkbasalt.tar.gz](https://github.com/DadSchoorse/vkBasalt/files/4775296/vkbasalt.tar.gz)

Do you know if there is something is wrong or missing on my end ?

Regards

**Comment by DadSchoorse** [comment]
> My config file (`~/.config/vkBasalt.conf`):

Try moving it to `~/.config/vkBasalt/vkBasalt.conf`.

**Comment by vinifmor** [comment]
It worked ! Thanks
