### ISSUE TITLE
X11 dependency issues

### ISSUE THREAD

**Issue by dustContributor** [DadSchoorse/vkBasalt#87]
Hi! I tried to build this in Debian (testing) x64, and I had the following issue: `meson` can't find the 'x11' dependency, because in Debian it's 'X11'

Changing the line in  [the build file](https://github.com/DadSchoorse/vkBasalt/blob/master/src/meson.build#L41) from `x11_dep = dependency('x11')` to `x11_dep = dependency('X11')` fixed it.

I don't know about `meson` so I can't propose a fix, it's just a bug report.

**Comment by DadSchoorse** [comment]
tbh, I have no clue what's going on here, the `dependency('X11')` causes issues on arch because meson finds `/usr/lib/libX11.so` for some reason and ofc linking to that fails.

**Comment by stephanlachnit** [comment]
> Hi! I tried to build this in Debian (testing) x64, and I had the following issue: meson can't find the 'x11' dependency, because in Debian it's 'X11'

No I don't think that is correct. Actually, I get build error with `dependency('X11')` (Debian Sid).
@dustContributor are you sure you have `libx11-dev` installed?

**Comment by John-Gee** [comment]
That indeed builds now fine on Arch for 32b, thanks!

**Comment by dustContributor** [comment]
> @dustContributor are you sure you have `libx11-dev` installed?

Yup! As I said, once I made the dependency upper case, it compiled. If I didn't have the libx11-dev package installed, it wouldn't have compiled either way.

In any case, if you see the relevant installed files of `libx11-dev` they are:

> /usr/include/X11/Xlib.h
> /usr/lib/x86_64-linux-gnu/libX11.a
> /usr/lib/x86_64-linux-gnu/libX11.so

In both cases using uppercase `X11` rather than `x11` as you say.

On the other hand, if you look at the pkgconfig file installed with the same package:

> /usr/lib/x86_64-linux-gnu/pkgconfig/x11.pc

Lowercase is being used.

I have no idea about the discrepancy here. Maybe version differences? I am using Debian testing but honestly I haven't upgraded a bunch of it in a while, it isn't `stable` old but it isn't current `testing` either. Maybe it's an issue with my system only, I don't have any other Debian install to try this on sadly.

**Comment by stephanlachnit** [comment]
> In any case, if you see the relevant installed files of `libx11-dev` they are:
> 
> > /usr/include/X11/Xlib.h
> > /usr/lib/x86_64-linux-gnu/libX11.a
> > /usr/lib/x86_64-linux-gnu/libX11.so
> 
> In both cases using uppercase `X11` rather than `x11` as you say.

The name of the library (or worse path) shouldn't be used to satisfy a dependency, like never. That's why there is pkg-config.

> On the other hand, if you look at the pkgconfig file installed with the same package:
> 
> > /usr/lib/x86_64-linux-gnu/pkgconfig/x11.pc
> 
> Lowercase is being used.

Yes, and it's lowercase on every system, since it's in the libx11 source package.

> I have no idea about the discrepancy here. Maybe version differences? I am using Debian testing but honestly I haven't upgraded a bunch of it in a while, it isn't `stable` old but it isn't current `testing` either. Maybe it's an issue with my system only, I don't have any other Debian install to try this on sadly.

No, it has nothing to do with versions. `libX11.so` probably has an uppercase X for historic reasons, it should be the same on Arch or any other distro.

As I already said, I don't know what you did that it worked with an uppercase X. Do you even have pkg-config installed? Check it with
```sh
apt list --installed pkg-config
```

I can imagine that Meson falls back to actual names of the library if pkg-config is not installed, and doesn't do that if pkg-config is installed. Please note that on Debian, installing Meson doesn't automatically install pkg-config, neither does build-essential.

**Comment by dustContributor** [comment]
> apt list --installed pkg-config
Listing... Done
pkg-config/testing,now 0.29.2-1 amd64 [installed]

> apt list --installed build-essential
Listing... Done

Oooh now we're onto something. I'll see later if I can clone the repo and try again with it installed.

**Comment by dustContributor** [comment]
A bit... uh... late, but it works. I was just missing those deps. Thank you for your work!
