### ISSUE TITLE
Cannot build 32bit on openSUSE Tubleweed

### ISSUE THREAD

**Issue by sputniktr02** [DadSchoorse/vkBasalt#89]
64 bit builds and installs fine but 32 bit fails.
There is no `usr/lib32/pkgconfig` path on openSUSE, there are lib and lib64, so I changed command to;
```
ASFLAGS=--32 CFLAGS=-m32 CXXFLAGS=-m32 PKG_CONFIG_PATH=/usr/lib/pkgconfig meson --prefix=/usr --buildtype=release --libdir=lib -Dwith_json=false builddir.32
ninja -C builddir.32 install
```
but it gives me this error:

> The Meson build system
> Version: 0.54.3
> Source dir: /home/user/Downloads/vkBasalt
> Build dir: /home/user/Downloads/vkBasalt/builddir.32
> Build type: native build
> Using 'PKG_CONFIG_PATH' from environment with value: '/usr/lib/pkgconfig'
> Using 'PKG_CONFIG_PATH' from environment with value: '/usr/lib/pkgconfig'
> Project name: vkBasalt
> Project version: undefined
> Using 'CFLAGS' from environment with value: '-m32'
> Using 'CXXFLAGS' from environment with value: '-m32'
> 
> meson.build:1:0: ERROR: Compiler c++ can not compile programs.
> 
> A full log can be found at /home/user/Downloads/vkBasalt/builddir.32/meson-logs/meson-log.txt

This is the meson log:
[meson-log.txt](https://github.com/DadSchoorse/vkBasalt/files/4840296/meson-log.txt)

Do I miss some dependencies? Sorry if there is something obvious that I miss.

**Comment by DadSchoorse** [comment]
First thing to check is if you have gcc with 32 bit support installed, I think it's called `gcc-32bit` on opensuse.

**Comment by sputniktr02** [comment]
It is already installed.

**Comment by DadSchoorse** [comment]
Honestly, I don't know anything about opensuse, I can't really help you with that.

**Comment by sputniktr02** [comment]
Sad to hear. By the way, can you reconsider releasing prebuild packages at least, they were working fine on openSUSE.

**Comment by sputniktr02** [comment]
@DadSchoorse  Update: I got past the error by installing **gcc-c++-32bit** package, however build still fails.
Here is the full terminal output:

[terminal-output.txt](https://github.com/DadSchoorse/vkBasalt/files/4853058/terminal-output.txt)

**Comment by DadSchoorse** [comment]
Oh, that might be the same issue as on 32 bit arch with `0.3.2`. Can you try `0.3.2.1` or master?

**Comment by sputniktr02** [comment]
I was trying the master with git clone. It's the same with 0.3.2 and 0.3.2.1. Am I still missing some dependencies? Because;
`/usr/lib/pkgconfig/` is empty
`/usr/lib64/pkgconfig/` contains a lot of files.

**Comment by DadSchoorse** [comment]
You are missing 32 bit libX11 or the linker can't find it.

**Comment by sputniktr02** [comment]
When I search for libX11, only these come up and they are already installed.

![Screenshot_20200710_112724](https://user-images.githubusercontent.com/31340272/87133856-95ae3780-c2a0-11ea-9d32-7f79c69ecb66.jpg)

I am out of ideas.
