### ISSUE TITLE
Cannot build 32b on Ubuntu 18.04

### ISSUE THREAD

**Issue by dairefagan** [DadSchoorse/vkBasalt#92]
Before installing 64b I input:

`sudo apt install build-essential gcc-multilib libx11-dev libx11-dev:i386 glslang-tools
snap install spirv-tools`

I have edited the 32b install command according to the instructions to:

`sudo ASFLAGS=--32 CFLAGS=-m32 CXXFLAGS=-m32 PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig meson --prefix=/usr --buildtype=release --libdir=lib/i386-linux-gnu -Dwith_json=false builddir.32`

but this outputs for me:

```
Build started at 2020-07-09T15:34:04.352186
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.51.2
Source dir: /mnt/freedom/Downloads/vkBasalt
Build dir: /mnt/freedom/Downloads/vkBasalt/builddir.32
Build type: native build
Project name: vkBasalt
Project version: undefined
Appending CFLAGS from environment: '-m32'
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc -m32 -pipe -D_FILE_OFFSET_BITS=64 /mnt/freedom/Downloads/vkBasalt/builddir.32/meson-private/sanitycheckc.c -o /mnt/freedom/Downloads/vkBasalt/builddir.32/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status

-----

meson.build:1:0: ERROR: Compiler cc can not compile programs.
```

I can see that I have gcc-multilib and build-essential already installed.

Is there something else I can try please?

**Comment by DadSchoorse** [comment]
mhm, it's probably missing some 32bit libraries. Maybe your missing `libgcc-*-dev:i386`, maybe `g++-multilib`.

**Comment by dairefagan** [comment]
> mhm, it's probably missing some 32bit libraries. Maybe you are missing `libgcc-*-dev:i386`, maybe `g++-multilib`.

Thanks, I installed both of those, same issue unfortunately.

**Comment by DadSchoorse** [comment]
mhm, I wonder if it's vkBasalt specific or if there's still a compiler issue. Can try to compile that simple hello world? Simply rename it to hello_world.cpp and use `g++ -m32 hello_world.cpp`, no output that means it worked.
[hello_world.cpp.txt](https://github.com/DadSchoorse/vkBasalt/files/4899335/hello_world.cpp.txt)

**Comment by alexeyza** [comment]
After following the same steps as @dairefagan, I have the same issue with the 32bit installation as the one described by him (the 64bit seems to have been installed okay). 
```shell
sudo ASFLAGS=--32 CFLAGS=-m32 CXXFLAGS=-m32 PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig meson --prefix=/usr --buildtype=release --libdir=lib/i386-linux-gnu -Dwith_json=false builddir.32
The Meson build system
Version: 0.54.3
Source dir: vkBasalt
Build dir: vkBasalt/builddir.32
Build type: native build
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/lib/i386-linux-gnu/pkgconfig'
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/lib/i386-linux-gnu/pkgconfig'
Project name: vkBasalt
Project version: undefined
Using 'CFLAGS' from environment with value: '-m32'
Using 'CXXFLAGS' from environment with value: '-m32'

meson.build:1:0: ERROR: Compiler c++ can not compile programs.

A full log can be found at vkBasalt/builddir.32/meson-logs/meson-log.txt

```
The `meson-log.txt` file had this:
```
Sanity check compile stderr:
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libstdc++.a when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
```

I also tried compiling the hello world example and got the following error (on Ubuntu 20.04):
```shell
In file included from hello_world.cpp:1:
/usr/include/c++/9/iostream:38:10: fatal error: bits/c++config.h: No such file or directory
   38 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by dairefagan** [comment]
daire@contraption:/mnt/freedom/Downloads$ g++ -m32 hello_world.cpp
In file included from hello_world.cpp:1:
/usr/include/c++/9/iostream:38:10: fatal error: bits/c++config.h: No such file or directory
   38 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

Trying a recommended solution from StackOverflow:

daire@contraption:/mnt/freedom/Downloads$ sudo apt-get install gcc-multilib g++-multilib
[sudo] password for daire: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++-multilib is already the newest version (4:7.4.0-1ubuntu2.3).
gcc-multilib is already the newest version (4:7.4.0-1ubuntu2.3).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

Someone on reddit has suggested lib32gcc may be missing though when I try to install it there are many packages that beging with that string though none matching 4.7 (in case they need to match)

**Comment by dairefagan** [comment]
helloworld.cpp now compiling for me after all or one of:

```
sudo apt --reinstall install gcc-multilib g++-multilib
sudo apt --reinstall install g++
sudo apt --reinstall install build-essential
```

**Comment by dairefagan** [comment]
Okay 32b vkBasalt has now compiled for me, although I am not exactly sure what worked. I was googling for solutions to the error messages meson was giving. The last thing I did was again reinstall build-essential, and gcc, and g++. Checking for installed packages for those:

```
daire@contraption:/mnt/freedom/Downloads/vkBasalt$ apt list --installed | grep gcc

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gcc/bionic-updates,bionic-security,now 4:7.4.0-1ubuntu2.3 amd64 [installed]
gcc-10-base/bionic,now 10.1.0-2ubuntu1~18.04 amd64 [installed,automatic]
gcc-4.8/bionic,now 4.8.5-4ubuntu8 amd64 [installed]
gcc-4.8-base/bionic,now 4.8.5-4ubuntu8 amd64 [installed,automatic]
gcc-5-base/bionic,now 5.5.0-12ubuntu1 i386 [installed,automatic]
gcc-6-base/bionic-updates,now 6.5.0-2ubuntu1~18.04 i386 [installed,automatic]
gcc-7/bionic-updates,bionic-security,now 7.5.0-3ubuntu1~18.04 amd64 [installed]
gcc-7-base/bionic-updates,bionic-security,now 7.5.0-3ubuntu1~18.04 amd64 [installed]
gcc-7-multilib/bionic-updates,bionic-security,now 7.5.0-3ubuntu1~18.04 amd64 [installed,automatic]
gcc-8/bionic-updates,bionic-security,now 8.4.0-1ubuntu1~18.04 amd64 [installed]
gcc-8-base/bionic-updates,bionic-security,now 8.4.0-1ubuntu1~18.04 amd64 [installed]
gcc-9/bionic,now 9.3.0-11ubuntu0~18.04.1 amd64 [installed]
gcc-9-base/bionic,now 9.3.0-11ubuntu0~18.04.1 amd64 [installed,automatic]
gcc-multilib/bionic-updates,bionic-security,now 4:7.4.0-1ubuntu2.3 amd64 [installed]
lib32gcc-7-dev/bionic-updates,bionic-security,now 7.5.0-3ubuntu1~18.04 amd64 [installed,automatic]
lib32gcc-s1/bionic,now 10.1.0-2ubuntu1~18.04 amd64 [installed,automatic]
lib32gcc1/bionic,now 1:10.1.0-2ubuntu1~18.04 amd64 [installed,automatic]
libgcc-10-dev/bionic,now 10.1.0-2ubuntu1~18.04 i386 [installed]
libgcc-4.8-dev/bionic,now 4.8.5-4ubuntu8 amd64 [installed,automatic]
libgcc-5-dev/bionic,now 5.5.0-12ubuntu1 i386 [installed]
libgcc-6-dev/bionic-updates,now 6.5.0-2ubuntu1~18.04 i386 [installed]
libgcc-7-dev/bionic-updates,bionic-security,now 7.5.0-3ubuntu1~18.04 amd64 [installed,automatic]
libgcc-8-dev/bionic-updates,bionic-security,now 8.4.0-1ubuntu1~18.04 amd64 [installed,automatic]
libgcc-9-dev/bionic,now 9.3.0-11ubuntu0~18.04.1 amd64 [installed,automatic]
libgcc-s1/bionic,now 10.1.0-2ubuntu1~18.04 amd64 [installed,automatic]
libgcc1/bionic,now 1:10.1.0-2ubuntu1~18.04 i386 [installed]
libx32gcc-4.8-dev/bionic,now 4.8.5-4ubuntu8 amd64 [installed]
libx32gcc-7-dev/bionic-updates,bionic-security,now 7.5.0-3ubuntu1~18.04 amd64 [installed,automatic]
libx32gcc-s1/bionic,now 10.1.0-2ubuntu1~18.04 amd64 [installed,automatic]
libx32gcc1/bionic,now 1:10.1.0-2ubuntu1~18.04 amd64 [installed,automatic]
daire@contraption:/mnt/freedom/Downloads/vkBasalt$ apt list --installed | grep g++

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

g++/bionic-updates,bionic-security,now 4:7.4.0-1ubuntu2.3 amd64 [installed]
g++-4.8/bionic,now 4.8.5-4ubuntu8 amd64 [installed]
g++-7/bionic-updates,bionic-security,now 7.5.0-3ubuntu1~18.04 amd64 [installed]
g++-7-multilib/bionic-updates,bionic-security,now 7.5.0-3ubuntu1~18.04 amd64 [installed,automatic]
g++-8/bionic-updates,bionic-security,now 8.4.0-1ubuntu1~18.04 amd64 [installed]
g++-9/bionic,now 9.3.0-11ubuntu0~18.04.1 amd64 [installed]
g++-multilib/bionic-updates,bionic-security,now 4:7.4.0-1ubuntu
```2.3 amd64 [installed]

**Comment by dairefagan** [comment]
Messy unedited terminal (I was testing apt-file search with a file from a related solution):

https://pastebin.ubuntu.com/p/NmVhnTNnVR/

**Comment by alexeyza** [comment]
> helloworld.cpp now compiling for me after all or one of:
> 
> ```
> sudo apt --reinstall install gcc-multilib g++-multilib
> sudo apt --reinstall install g++
> sudo apt --reinstall install build-essential
> ```

@dairefagan you were right, I was missing `g++-multilib`. 
Now, both 32 bit and 64 bit compile correctly (also the hello world example).

So, to recap: on Ubuntu 20.04 I had to first do
```shell
sudo apt install build-essential gcc-multilib libx11-dev libx11-dev:i386 glslang-tools spirv-tools g++-multilib
```
(I actually already had `build-essential` and `libx11-dev` previously installed, probably `g++` as well), 
and then follow the [build instructions](https://github.com/DadSchoorse/vkBasalt#building) for vkBasalt.

**Comment by Ahmed-E-86** [comment]
> > helloworld.cpp now compiling for me after all or one of:
> > ```
> > sudo apt --reinstall install gcc-multilib g++-multilib
> > sudo apt --reinstall install g++
> > sudo apt --reinstall install build-essential
> > ```
> 
> @dairefagan you were right, I was missing `g++-multilib`.
> Now, both 32 bit and 64 bit compile correctly (also the hello world example).
> 
> So, to recap: on Ubuntu 20.04 I had to first do
> 
> ```shell
> sudo apt install build-essential gcc-multilib libx11-dev libx11-dev:i386 glslang-tools spirv-tools g++-multilib
> ```
> 
> (I actually already had `build-essential` and `libx11-dev` previously installed, probably `g++` as well),
> and then follow the [build instructions](https://github.com/DadSchoorse/vkBasalt#building) for vkBasalt.

Actually, it is `spirv-headers` not `spirv-tools`
