### ISSUE TITLE
Having an error message when downloading code "ninja -C builddir install" in terminal making it fail.

### ISSUE THREAD

**Issue by Edjango** [DadSchoorse/vkBasalt#94]
When attempting to download code "ninja -C builddir install" the following message appears " c++: error: unrecognized command line option ‘-std=c++2a’; did you mean ‘-std=c++03’?". Is there any solution to this or something that I did wrong?

**Comment by stephanlachnit** [comment]
A bit more information would be helpful to resolve this. Which distro and compiler are you using? I can imagine it's just out of date and doesn't now the `c++2a` (aka C++20) standard.

**Comment by Edjango** [comment]
I use linux mint 19 and as for a compiler.. I have no idea how to check that I'm sorry.

**Comment by stephanlachnit** [comment]
So it's Ubuntu 18.04 based, that could be the problem. Can you type
```
apt list --installed g++
```

**Comment by Edjango** [comment]
I'm afraid the same error message came up as before

**Comment by stephanlachnit** [comment]
No, I want the output of that.

**Comment by agucova** [comment]
In my case, Linuxbrew on Ubuntu 20.04 was overwriting the default gcc and g++ versions to 4. (Not sure what the default on 20.04 is, anyway)

Overwriting the `CC` and `CXX` variables to their correct 9 counterparts (which support `c++2a`) seemed to work.

```shell
CXX=g++-9 CC=gcc-9 meson --buildtype=release --prefix=/usr builddir
ninja -C builddir install
```
